/******************************************************************* 
 * C-file generated by Protoc for Embedded C.                      *
 * Version 0.2 (2012-01-31)                                        *
 *                                                                 *
 * Copyright (c) 2009-2012                                         *
 * Technische Universitaet Muenchen                                *
 * http://www4.in.tum.de/                                          *
 *                                                                 *
 * Source : rfid_board_api.proto
 * Package: 
 *                                                                 *
 * Do not edit.                                                    *
 *******************************************************************/

#include "rfid_board_api.h"

/*******************************************************************
 * General functions
 *******************************************************************/
 
void _memset(void *msg_ptr, char init_val, unsigned int size) {
    int i;
    for(i = 0; i < size; ++ i)
        *((char*)msg_ptr + i) = init_val;
}

int varint_packed_size(unsigned long value) {
    if ((value & (0xffffffff <<  7)) == 0) return 1;
    if ((value & (0xffffffff << 14)) == 0) return 2;
    if ((value & (0xffffffff << 21)) == 0) return 3;
    if ((value & (0xffffffff << 28)) == 0) return 4;
    return 5;  
}

int write_raw_byte(char value, void *_buffer, int offset) {
    *((char *)_buffer + offset) = value;
    return ++offset;
}

/** Write a little-endian 32-bit integer. */
int write_raw_little_endian32(unsigned long value, void *_buffer, int offset) {
    offset = write_raw_byte((char)((value      ) & 0xFF), _buffer, offset);
    offset = write_raw_byte((char)((value >>  8) & 0xFF), _buffer, offset);
    offset = write_raw_byte((char)((value >> 16) & 0xFF), _buffer, offset);
    offset = write_raw_byte((char)((value >> 24) & 0xFF), _buffer, offset);
    
    return offset;
}

/** Write a little-endian 64-bit integer. */
int write_raw_little_endian64(unsigned long long value, void *_buffer, int offset) {
    offset = write_raw_byte((char)((value      ) & 0xFF), _buffer, offset);
    offset = write_raw_byte((char)((value >>  8) & 0xFF), _buffer, offset);
    offset = write_raw_byte((char)((value >> 16) & 0xFF), _buffer, offset);
    offset = write_raw_byte((char)((value >> 24) & 0xFF), _buffer, offset);
    offset = write_raw_byte((char)((value >> 32) & 0xFF), _buffer, offset);
    offset = write_raw_byte((char)((value >> 40) & 0xFF), _buffer, offset);
    offset = write_raw_byte((char)((value >> 48) & 0xFF), _buffer, offset);
    offset = write_raw_byte((char)((value >> 56) & 0xFF), _buffer, offset);
    
    return offset;
}

int write_raw_varint32(unsigned long value, void *_buffer, int offset) {
    while (1) {
        if ((value & ~0x7F) == 0) {
            offset = write_raw_byte((char)value, _buffer, offset);
            return offset;
        } else {
            offset = write_raw_byte((char)((value & 0x7F) | 0x80), _buffer, offset);
            value = value >> 7;
        }
    }
    return offset;
}

int write_raw_varint64(unsigned long long value, void *_buffer, int offset) {
    while (1) {
        if ((value & ~0x7FL) == 0) {
            offset = write_raw_byte((char)value, _buffer, offset);
            return offset;
        } else {
            offset = write_raw_byte((char)((value & 0x7F) | 0x80), _buffer, offset);
            value = value >> 7;
        }
    }
    return offset;
}

int write_raw_bytes(char *bytes, int bytes_size, void *_buffer, int offset) {
    int i; 
    for(i = 0; i < bytes_size; ++ i) {
        offset = write_raw_byte((char)*(bytes + i), _buffer, offset);
    }
    
    return offset;   
}

unsigned long encode_zig_zag32(signed long n) {
    // Note:  the right-shift must be arithmetic
    return (n << 1) ^ (n >> 31);
}

unsigned long long encode_zig_zag64(signed long long n) {
    // Note:  the right-shift must be arithmetic
    return (n << 1) ^ (n >> 63);
} 

signed long decode_zig_zag32(unsigned long n) {
    return (n >> 1) ^ -(n & 1);
}

signed long long decode_zig_zag64(unsigned long long n) {
    return (n >> 1) ^ -(n & 1);
}

int read_raw_byte(char *tag, void *_buffer, int offset) {
    *tag = *((char *) _buffer + offset);
    
    return ++offset;
}

/** Read a 32-bit little-endian integer from the stream. */
int read_raw_little_endian32(unsigned long *tag, void *_buffer, int offset) {
    offset = read_raw_byte((char *)tag, _buffer, offset);
    char b1 = (char) *tag;
    offset = read_raw_byte((char *)tag, _buffer, offset);
    char b2 = (char) *tag;
    offset = read_raw_byte((char *)tag, _buffer, offset);
    char b3 = (char) *tag;
    offset = read_raw_byte((char *)tag, _buffer, offset);
    char b4 = (char) *tag;
    
    *tag = (((unsigned long)b1 & 0xff)      ) |
           (((unsigned long)b2 & 0xff) <<  8) |
           (((unsigned long)b3 & 0xff) << 16) |
           (((unsigned long)b4 & 0xff) << 24);
           
    return offset;
}

/** Read a 64-bit little-endian integer from the stream. */
int read_raw_little_endian64(unsigned long long *tag, void *_buffer, int offset) {
    offset = read_raw_byte((char *)tag, _buffer, offset);
    char b1 = (char) *tag;
    offset = read_raw_byte((char *)tag, _buffer, offset);
    char b2 = (char) *tag;
    offset = read_raw_byte((char *)tag, _buffer, offset);
    char b3 = (char) *tag;
    offset = read_raw_byte((char *)tag, _buffer, offset);
    char b4 = (char) *tag;
    offset = read_raw_byte((char *)tag, _buffer, offset);
    char b5 = (char) *tag;
    offset = read_raw_byte((char *)tag, _buffer, offset);
    char b6 = (char) *tag;
    offset = read_raw_byte((char *)tag, _buffer, offset);
    char b7 = (char) *tag;
    offset = read_raw_byte((char *)tag, _buffer, offset);
    char b8 = (char) *tag;
    
    *tag = (((unsigned long long)b1 & 0xff)      ) |
           (((unsigned long long)b2 & 0xff) <<  8) |
           (((unsigned long long)b3 & 0xff) << 16) |
           (((unsigned long long)b4 & 0xff) << 24) |
           (((unsigned long long)b5 & 0xff) << 32) |
           (((unsigned long long)b6 & 0xff) << 40) |
           (((unsigned long long)b7 & 0xff) << 48) |
           (((unsigned long long)b8 & 0xff) << 56);
           
    return offset;
}

int read_raw_varint32(unsigned long *tag, void *_buffer, int offset) {
    signed char result;
    
    offset = read_raw_byte((char *)&result, _buffer, offset);
    if (result >= 0) {
        *tag = result;
        return offset;
    }
    *tag = result & 0x7f;
    offset = read_raw_byte((char *)&result, _buffer, offset);
    if (result >= 0) {
        *tag |= result << 7;
    } else {
        *tag |= (result & 0x7f) << 7;
        offset = read_raw_byte((char *)&result, _buffer, offset);
        if (result >= 0) {
            *tag |= result << 14;
        } else {
            *tag |= (result & 0x7f) << 14;
            offset = read_raw_byte((char *)&result, _buffer, offset);
            if (result >= 0) {
                *tag |= ((unsigned long)result) << 21;
            } else {
                *tag |= (((unsigned long)result) & 0x7f) << 21;
                offset = read_raw_byte((char *)&result, _buffer, offset);
                *tag |= ((unsigned long)result) << 28;
                if (result < 0) {
                    // Discard upper 32 bits.
                    int i;
                    for (i = 0; i < 5; ++ i) {
                        offset = read_raw_byte((char *)&result, _buffer, offset);
                        if (result >= 0) {
                            return offset;
                        }
                    }
                    //invalid state
                }
            }
        }
    }
    return offset;
}

int read_raw_varint64(unsigned long long *tag, void *_buffer, int offset) {
    short shift = 0;
    signed char b;
    *tag = 0;
    while (shift < 64) {
        offset = read_raw_byte((char *)&b, _buffer, offset);
        *tag |= (unsigned long long)(b & 0x7F) << shift;
        if ((b & 0x80) == 0) {
            return offset;
        }
        shift += 7;
    }
    //return error code.
    return -1;
}

int can_read_raw_varint32(void *_buffer, int offset, int length) {
    signed char c;
    
    // Bound length to valid range [0..5].
    if (length < 0) length = 0; else
    if (length > 5) length = 5;
    
    while (length > 0) {
        offset = read_raw_byte((char *)&c, _buffer, offset);
        if (c >= 0) {
            return 1; // Can read (1 == true).
        }
        length--;
    }
    
    return 0; // Cannot read (0 == false).
}

int can_read_raw_varint64(void *_buffer, int offset, int length) {
    signed char c;
    
    // Bound length to valid range [0..5].
    if (length < 0) length = 0; else
    if (length > 10) length = 10;
    
    while (length > 0) {
        offset = read_raw_byte((char *)&c, _buffer, offset);
        if (c >= 0) {
            return 1; // Can read (1 == true).
        }
        length--;
    }
    
    return 0; // Cannot read (0 == false).
}

int Message_can_read_delimited_from(void *_buffer, int offset, int length) {
    unsigned long size;
    int payload_offset;

    if (length <= 0) return 0; // Cannot read from empty or invalid message.

    if (!can_read_raw_varint32(_buffer, offset, length)) {
        return 0; // Could not even read the preceding size as varint32.
    }

    payload_offset = read_raw_varint32(&size, _buffer, offset);
    length = length - (payload_offset - offset);

    return (length >= size) ? 1 : 0;
}

unsigned long Message_get_delimited_size(void *_buffer, int offset) {
    unsigned long size = 0;
    int old_offset = offset;
    
    offset = read_raw_varint32(&size, _buffer, offset);
    
    return size + offset - old_offset;
}


/*******************************************************************
 * Enum: rfid_board_api.proto, line 143
 *******************************************************************/
int RFIDMsgName_write_with_tag(enum RFIDMsgName *_RFIDMsgName, void *_buffer, int offset, int tag) {
    /* Write tag.*/
    offset = write_raw_varint32((tag<<3)+0, _buffer, offset);
    /* Write content.*/
    offset = write_raw_varint32(*_RFIDMsgName, _buffer, offset);
    
    return offset;
}

/*******************************************************************
 * Enum: rfid_board_api.proto, line 169
 *******************************************************************/
int RFIDMsgType_write_with_tag(enum RFIDMsgType *_RFIDMsgType, void *_buffer, int offset, int tag) {
    /* Write tag.*/
    offset = write_raw_varint32((tag<<3)+0, _buffer, offset);
    /* Write content.*/
    offset = write_raw_varint32(*_RFIDMsgType, _buffer, offset);
    
    return offset;
}

/*******************************************************************
 * Enum: rfid_board_api.proto, line 190
 *******************************************************************/
int RFIDMsgRoute_write_with_tag(enum RFIDMsgRoute *_RFIDMsgRoute, void *_buffer, int offset, int tag) {
    /* Write tag.*/
    offset = write_raw_varint32((tag<<3)+0, _buffer, offset);
    /* Write content.*/
    offset = write_raw_varint32(*_RFIDMsgRoute, _buffer, offset);
    
    return offset;
}

/*******************************************************************
 * Enum: rfid_board_api.proto, line 203
 *******************************************************************/
int RFIDFieldState_write_with_tag(enum RFIDFieldState *_RFIDFieldState, void *_buffer, int offset, int tag) {
    /* Write tag.*/
    offset = write_raw_varint32((tag<<3)+0, _buffer, offset);
    /* Write content.*/
    offset = write_raw_varint32(*_RFIDFieldState, _buffer, offset);
    
    return offset;
}

/*******************************************************************
 * Message: rfid_board_api.proto, line 256
 *******************************************************************/
int RFIDBasicMsg_write(struct RFIDBasicMsg *_RFIDBasicMsg, void *_buffer, int offset) {
    /* Write content of each message element.*/
    offset = RFIDMsgName_write_with_tag(&_RFIDBasicMsg->_msgName, _buffer, offset, 1);
    offset = write_raw_varint32((2<<3)+0, _buffer, offset);
    offset = write_raw_varint32(_RFIDBasicMsg->_msgID, _buffer, offset);

    offset = RFIDMsgType_write_with_tag(&_RFIDBasicMsg->_msgType, _buffer, offset, 3);
    offset = RFIDMsgRoute_write_with_tag(&_RFIDBasicMsg->_msgRoute, _buffer, offset, 4);
    offset = RFIDMsgName_write_with_tag(&_RFIDBasicMsg->_msgPayload, _buffer, offset, 5);
    
    return offset;
}

int RFIDBasicMsg_write_with_tag(struct RFIDBasicMsg *_RFIDBasicMsg, void *_buffer, int offset, int tag) {
    /* Write tag.*/
    offset = write_raw_varint32((tag<<3)+2, _buffer, offset);
    /* Write content.*/
    offset = RFIDBasicMsg_write_delimited_to(_RFIDBasicMsg, _buffer, offset);
    
    return offset;
}

int RFIDBasicMsg_write_delimited_to(struct RFIDBasicMsg *_RFIDBasicMsg, void *_buffer, int offset) {
    int i, shift, new_offset, size;
    
    new_offset = RFIDBasicMsg_write(_RFIDBasicMsg, _buffer, offset);
    size = new_offset - offset;
    shift = (size > 127) ? 2 : 1;
    for (i = new_offset - 1; i >= offset; -- i)
        *((char *)_buffer + i + shift) = *((char *)_buffer + i);
    
    write_raw_varint32((unsigned long) size, _buffer, offset);         
        
    return new_offset + shift;
}

void RFIDBasicMsg_clear(struct RFIDBasicMsg *_RFIDBasicMsg) {
    _memset(_RFIDBasicMsg, 0, sizeof(struct RFIDBasicMsg));
}

int RFIDBasicMsg_read(void *_buffer, struct RFIDBasicMsg *_RFIDBasicMsg, int offset, int limit) {
    int i = 0;
    unsigned long tag = i;

    /* Reset all attributes to 0 in advance. */
    RFIDBasicMsg_clear(_RFIDBasicMsg);

    /* Read/interpret all attributes from buffer offset until upper limit is reached. */
    while(offset < limit) {
        offset = read_raw_varint32(&tag, _buffer, offset);
        tag = tag>>3;
        switch(tag){
            //tag of: _RFIDBasicMsg._msgName 
            case 1 :
                offset = read_raw_varint32(&tag, _buffer, offset);
                _RFIDBasicMsg->_msgName = tag;
                break;
            //tag of: _RFIDBasicMsg._msgID 
            case 2 :
                offset = read_raw_varint32(&tag, _buffer, offset);
                _RFIDBasicMsg->_msgID = tag;
                break;
            //tag of: _RFIDBasicMsg._msgType 
            case 3 :
                offset = read_raw_varint32(&tag, _buffer, offset);
                _RFIDBasicMsg->_msgType = tag;
                break;
            //tag of: _RFIDBasicMsg._msgRoute 
            case 4 :
                offset = read_raw_varint32(&tag, _buffer, offset);
                _RFIDBasicMsg->_msgRoute = tag;
                break;
            //tag of: _RFIDBasicMsg._msgPayload 
            case 5 :
                offset = read_raw_varint32(&tag, _buffer, offset);
                _RFIDBasicMsg->_msgPayload = tag;
                break;
        }
    }
    
    return offset;
}

int RFIDBasicMsg_read_delimited_from(void *_buffer, struct RFIDBasicMsg *_RFIDBasicMsg, int offset) {
    unsigned long size;
    
    offset = read_raw_varint32(&size, _buffer, offset);
    RFIDBasicMsg_read(_buffer, _RFIDBasicMsg, offset, size + offset);
    
    return offset + size;
}


/*******************************************************************
 * Message: rfid_board_api.proto, line 280
 *******************************************************************/
int RFIDBasicPayloadMsg_write(struct RFIDBasicPayloadMsg *_RFIDBasicPayloadMsg, void *_buffer, int offset) {
    /* Write content of each message element.*/
    offset = write_raw_varint32((1<<3)+0, _buffer, offset);
    offset = write_raw_varint32(_RFIDBasicPayloadMsg->_errorCode, _buffer, offset);

    
    return offset;
}

int RFIDBasicPayloadMsg_write_with_tag(struct RFIDBasicPayloadMsg *_RFIDBasicPayloadMsg, void *_buffer, int offset, int tag) {
    /* Write tag.*/
    offset = write_raw_varint32((tag<<3)+2, _buffer, offset);
    /* Write content.*/
    offset = RFIDBasicPayloadMsg_write_delimited_to(_RFIDBasicPayloadMsg, _buffer, offset);
    
    return offset;
}

int RFIDBasicPayloadMsg_write_delimited_to(struct RFIDBasicPayloadMsg *_RFIDBasicPayloadMsg, void *_buffer, int offset) {
    int i, shift, new_offset, size;
    
    new_offset = RFIDBasicPayloadMsg_write(_RFIDBasicPayloadMsg, _buffer, offset);
    size = new_offset - offset;
    shift = (size > 127) ? 2 : 1;
    for (i = new_offset - 1; i >= offset; -- i)
        *((char *)_buffer + i + shift) = *((char *)_buffer + i);
    
    write_raw_varint32((unsigned long) size, _buffer, offset);         
        
    return new_offset + shift;
}

void RFIDBasicPayloadMsg_clear(struct RFIDBasicPayloadMsg *_RFIDBasicPayloadMsg) {
    _memset(_RFIDBasicPayloadMsg, 0, sizeof(struct RFIDBasicPayloadMsg));
}

int RFIDBasicPayloadMsg_read(void *_buffer, struct RFIDBasicPayloadMsg *_RFIDBasicPayloadMsg, int offset, int limit) {
    int i = 0;
    unsigned long tag = i;

    /* Reset all attributes to 0 in advance. */
    RFIDBasicPayloadMsg_clear(_RFIDBasicPayloadMsg);

    /* Read/interpret all attributes from buffer offset until upper limit is reached. */
    while(offset < limit) {
        offset = read_raw_varint32(&tag, _buffer, offset);
        tag = tag>>3;
        switch(tag){
            //tag of: _RFIDBasicPayloadMsg._errorCode 
            case 1 :
                offset = read_raw_varint32(&tag, _buffer, offset);
                _RFIDBasicPayloadMsg->_errorCode = tag;
                break;
        }
    }
    
    return offset;
}

int RFIDBasicPayloadMsg_read_delimited_from(void *_buffer, struct RFIDBasicPayloadMsg *_RFIDBasicPayloadMsg, int offset) {
    unsigned long size;
    
    offset = read_raw_varint32(&size, _buffer, offset);
    RFIDBasicPayloadMsg_read(_buffer, _RFIDBasicPayloadMsg, offset, size + offset);
    
    return offset + size;
}


/*******************************************************************
 * Message: rfid_board_api.proto, line 326
 *******************************************************************/
int RFIDCommTestPayloadMsg_write(struct RFIDCommTestPayloadMsg *_RFIDCommTestPayloadMsg, void *_buffer, int offset) {
    /* Write content of each message element.*/
    offset = write_raw_varint32((1<<3)+0, _buffer, offset);
    offset = write_raw_varint32(_RFIDCommTestPayloadMsg->_errorCode, _buffer, offset);

    offset = write_raw_varint32((2<<3)+0, _buffer, offset);
    offset = write_raw_varint32(_RFIDCommTestPayloadMsg->_payload, _buffer, offset);

    
    return offset;
}

int RFIDCommTestPayloadMsg_write_with_tag(struct RFIDCommTestPayloadMsg *_RFIDCommTestPayloadMsg, void *_buffer, int offset, int tag) {
    /* Write tag.*/
    offset = write_raw_varint32((tag<<3)+2, _buffer, offset);
    /* Write content.*/
    offset = RFIDCommTestPayloadMsg_write_delimited_to(_RFIDCommTestPayloadMsg, _buffer, offset);
    
    return offset;
}

int RFIDCommTestPayloadMsg_write_delimited_to(struct RFIDCommTestPayloadMsg *_RFIDCommTestPayloadMsg, void *_buffer, int offset) {
    int i, shift, new_offset, size;
    
    new_offset = RFIDCommTestPayloadMsg_write(_RFIDCommTestPayloadMsg, _buffer, offset);
    size = new_offset - offset;
    shift = (size > 127) ? 2 : 1;
    for (i = new_offset - 1; i >= offset; -- i)
        *((char *)_buffer + i + shift) = *((char *)_buffer + i);
    
    write_raw_varint32((unsigned long) size, _buffer, offset);         
        
    return new_offset + shift;
}

void RFIDCommTestPayloadMsg_clear(struct RFIDCommTestPayloadMsg *_RFIDCommTestPayloadMsg) {
    _memset(_RFIDCommTestPayloadMsg, 0, sizeof(struct RFIDCommTestPayloadMsg));
}

int RFIDCommTestPayloadMsg_read(void *_buffer, struct RFIDCommTestPayloadMsg *_RFIDCommTestPayloadMsg, int offset, int limit) {
    int i = 0;
    unsigned long tag = i;

    /* Reset all attributes to 0 in advance. */
    RFIDCommTestPayloadMsg_clear(_RFIDCommTestPayloadMsg);

    /* Read/interpret all attributes from buffer offset until upper limit is reached. */
    while(offset < limit) {
        offset = read_raw_varint32(&tag, _buffer, offset);
        tag = tag>>3;
        switch(tag){
            //tag of: _RFIDCommTestPayloadMsg._errorCode 
            case 1 :
                offset = read_raw_varint32(&tag, _buffer, offset);
                _RFIDCommTestPayloadMsg->_errorCode = tag;
                break;
            //tag of: _RFIDCommTestPayloadMsg._payload 
            case 2 :
                offset = read_raw_varint32(&tag, _buffer, offset);
                _RFIDCommTestPayloadMsg->_payload = tag;
                break;
        }
    }
    
    return offset;
}

int RFIDCommTestPayloadMsg_read_delimited_from(void *_buffer, struct RFIDCommTestPayloadMsg *_RFIDCommTestPayloadMsg, int offset) {
    unsigned long size;
    
    offset = read_raw_varint32(&size, _buffer, offset);
    RFIDCommTestPayloadMsg_read(_buffer, _RFIDCommTestPayloadMsg, offset, size + offset);
    
    return offset + size;
}


/*******************************************************************
 * Message: rfid_board_api.proto, line 350
 *******************************************************************/
int RFIDFieldStatePayloadMsg_write(struct RFIDFieldStatePayloadMsg *_RFIDFieldStatePayloadMsg, void *_buffer, int offset) {
    /* Write content of each message element.*/
    offset = write_raw_varint32((1<<3)+0, _buffer, offset);
    offset = write_raw_varint32(_RFIDFieldStatePayloadMsg->_errorCode, _buffer, offset);

    offset = RFIDFieldState_write_with_tag(&_RFIDFieldStatePayloadMsg->_fieldState, _buffer, offset, 2);
    
    return offset;
}

int RFIDFieldStatePayloadMsg_write_with_tag(struct RFIDFieldStatePayloadMsg *_RFIDFieldStatePayloadMsg, void *_buffer, int offset, int tag) {
    /* Write tag.*/
    offset = write_raw_varint32((tag<<3)+2, _buffer, offset);
    /* Write content.*/
    offset = RFIDFieldStatePayloadMsg_write_delimited_to(_RFIDFieldStatePayloadMsg, _buffer, offset);
    
    return offset;
}

int RFIDFieldStatePayloadMsg_write_delimited_to(struct RFIDFieldStatePayloadMsg *_RFIDFieldStatePayloadMsg, void *_buffer, int offset) {
    int i, shift, new_offset, size;
    
    new_offset = RFIDFieldStatePayloadMsg_write(_RFIDFieldStatePayloadMsg, _buffer, offset);
    size = new_offset - offset;
    shift = (size > 127) ? 2 : 1;
    for (i = new_offset - 1; i >= offset; -- i)
        *((char *)_buffer + i + shift) = *((char *)_buffer + i);
    
    write_raw_varint32((unsigned long) size, _buffer, offset);         
        
    return new_offset + shift;
}

void RFIDFieldStatePayloadMsg_clear(struct RFIDFieldStatePayloadMsg *_RFIDFieldStatePayloadMsg) {
    _memset(_RFIDFieldStatePayloadMsg, 0, sizeof(struct RFIDFieldStatePayloadMsg));
}

int RFIDFieldStatePayloadMsg_read(void *_buffer, struct RFIDFieldStatePayloadMsg *_RFIDFieldStatePayloadMsg, int offset, int limit) {
    int i = 0;
    unsigned long tag = i;

    /* Reset all attributes to 0 in advance. */
    RFIDFieldStatePayloadMsg_clear(_RFIDFieldStatePayloadMsg);

    /* Read/interpret all attributes from buffer offset until upper limit is reached. */
    while(offset < limit) {
        offset = read_raw_varint32(&tag, _buffer, offset);
        tag = tag>>3;
        switch(tag){
            //tag of: _RFIDFieldStatePayloadMsg._errorCode 
            case 1 :
                offset = read_raw_varint32(&tag, _buffer, offset);
                _RFIDFieldStatePayloadMsg->_errorCode = tag;
                break;
            //tag of: _RFIDFieldStatePayloadMsg._fieldState 
            case 2 :
                offset = read_raw_varint32(&tag, _buffer, offset);
                _RFIDFieldStatePayloadMsg->_fieldState = tag;
                break;
        }
    }
    
    return offset;
}

int RFIDFieldStatePayloadMsg_read_delimited_from(void *_buffer, struct RFIDFieldStatePayloadMsg *_RFIDFieldStatePayloadMsg, int offset) {
    unsigned long size;
    
    offset = read_raw_varint32(&size, _buffer, offset);
    RFIDFieldStatePayloadMsg_read(_buffer, _RFIDFieldStatePayloadMsg, offset, size + offset);
    
    return offset + size;
}
