/******************************************************************************* 
 * File generated by Protoc for Embedded C and split by protobuf_lib_splitter.py
 * This file contains only the functionality of protobuf-c so that is specific
 * to the protocol.  It can  be compiled into a separate library from the core 
 * to prevent symbol crashes between multiple different protobuf generated 
 * libraries.
 *                                                   
 * Copyright (c) 2009-2012
 * Technische Universitaet Muenchen
 * http://www4.in.tum.de/
 * Copyright (c) 2013
 * Datacard Group
 *                                                                                                                                  
 * Do not edit.                                                                
 ******************************************************************************/
/******************************************************************* 
 * C-file generated by Protoc for Embedded C.                      *
 * Version 0.2 (2012-01-31)                                        *
 *                                                                 *
 * Copyright (c) 2009-2012                                         *
 * Technische Universitaet Muenchen                                *
 * http://www4.in.tum.de/                                          *
 *                                                                 *
 * Source : rfid_board_api.proto
 * Package: 
 *                                                                 *
 * Do not edit.                                                    *
 *******************************************************************/

#include "rfid_board_api.h"
#include "protobuf_core.h
/*******************************************************************
 * Enum: rfid_board_api.proto, line 143
 *******************************************************************/
int RFIDMsgName_write_with_tag(enum RFIDMsgName *_RFIDMsgName, void *_buffer, int offset, int tag) {
    /* Write tag.*/
    offset = write_raw_varint32((tag<<3)+0, _buffer, offset);
    /* Write content.*/
    offset = write_raw_varint32(*_RFIDMsgName, _buffer, offset);
    
    return offset;
}

/*******************************************************************
 * Enum: rfid_board_api.proto, line 169
 *******************************************************************/
int RFIDMsgType_write_with_tag(enum RFIDMsgType *_RFIDMsgType, void *_buffer, int offset, int tag) {
    /* Write tag.*/
    offset = write_raw_varint32((tag<<3)+0, _buffer, offset);
    /* Write content.*/
    offset = write_raw_varint32(*_RFIDMsgType, _buffer, offset);
    
    return offset;
}

/*******************************************************************
 * Enum: rfid_board_api.proto, line 190
 *******************************************************************/
int RFIDMsgRoute_write_with_tag(enum RFIDMsgRoute *_RFIDMsgRoute, void *_buffer, int offset, int tag) {
    /* Write tag.*/
    offset = write_raw_varint32((tag<<3)+0, _buffer, offset);
    /* Write content.*/
    offset = write_raw_varint32(*_RFIDMsgRoute, _buffer, offset);
    
    return offset;
}

/*******************************************************************
 * Enum: rfid_board_api.proto, line 203
 *******************************************************************/
int RFIDFieldState_write_with_tag(enum RFIDFieldState *_RFIDFieldState, void *_buffer, int offset, int tag) {
    /* Write tag.*/
    offset = write_raw_varint32((tag<<3)+0, _buffer, offset);
    /* Write content.*/
    offset = write_raw_varint32(*_RFIDFieldState, _buffer, offset);
    
    return offset;
}

/*******************************************************************
 * Message: rfid_board_api.proto, line 256
 *******************************************************************/
int RFIDBasicMsg_write(struct RFIDBasicMsg *_RFIDBasicMsg, void *_buffer, int offset) {
    /* Write content of each message element.*/
    offset = RFIDMsgName_write_with_tag(&_RFIDBasicMsg->_msgName, _buffer, offset, 1);
    offset = write_raw_varint32((2<<3)+0, _buffer, offset);
    offset = write_raw_varint32(_RFIDBasicMsg->_msgID, _buffer, offset);

    offset = RFIDMsgType_write_with_tag(&_RFIDBasicMsg->_msgType, _buffer, offset, 3);
    offset = RFIDMsgRoute_write_with_tag(&_RFIDBasicMsg->_msgRoute, _buffer, offset, 4);
    offset = RFIDMsgName_write_with_tag(&_RFIDBasicMsg->_msgPayload, _buffer, offset, 5);
    
    return offset;
}

int RFIDBasicMsg_write_with_tag(struct RFIDBasicMsg *_RFIDBasicMsg, void *_buffer, int offset, int tag) {
    /* Write tag.*/
    offset = write_raw_varint32((tag<<3)+2, _buffer, offset);
    /* Write content.*/
    offset = RFIDBasicMsg_write_delimited_to(_RFIDBasicMsg, _buffer, offset);
    
    return offset;
}

int RFIDBasicMsg_write_delimited_to(struct RFIDBasicMsg *_RFIDBasicMsg, void *_buffer, int offset) {
    int i, shift, new_offset, size;
    
    new_offset = RFIDBasicMsg_write(_RFIDBasicMsg, _buffer, offset);
    size = new_offset - offset;
    shift = (size > 127) ? 2 : 1;
    for (i = new_offset - 1; i >= offset; -- i)
        *((char *)_buffer + i + shift) = *((char *)_buffer + i);
    
    write_raw_varint32((unsigned long) size, _buffer, offset);         
        
    return new_offset + shift;
}

void RFIDBasicMsg_clear(struct RFIDBasicMsg *_RFIDBasicMsg) {
    _memset(_RFIDBasicMsg, 0, sizeof(struct RFIDBasicMsg));
}

int RFIDBasicMsg_read(void *_buffer, struct RFIDBasicMsg *_RFIDBasicMsg, int offset, int limit) {
    int i = 0;
    unsigned long tag = i;

    /* Reset all attributes to 0 in advance. */
    RFIDBasicMsg_clear(_RFIDBasicMsg);

    /* Read/interpret all attributes from buffer offset until upper limit is reached. */
    while(offset < limit) {
        offset = read_raw_varint32(&tag, _buffer, offset);
        tag = tag>>3;
        switch(tag){
            //tag of: _RFIDBasicMsg._msgName 
            case 1 :
                offset = read_raw_varint32(&tag, _buffer, offset);
                _RFIDBasicMsg->_msgName = tag;
                break;
            //tag of: _RFIDBasicMsg._msgID 
            case 2 :
                offset = read_raw_varint32(&tag, _buffer, offset);
                _RFIDBasicMsg->_msgID = tag;
                break;
            //tag of: _RFIDBasicMsg._msgType 
            case 3 :
                offset = read_raw_varint32(&tag, _buffer, offset);
                _RFIDBasicMsg->_msgType = tag;
                break;
            //tag of: _RFIDBasicMsg._msgRoute 
            case 4 :
                offset = read_raw_varint32(&tag, _buffer, offset);
                _RFIDBasicMsg->_msgRoute = tag;
                break;
            //tag of: _RFIDBasicMsg._msgPayload 
            case 5 :
                offset = read_raw_varint32(&tag, _buffer, offset);
                _RFIDBasicMsg->_msgPayload = tag;
                break;
        }
    }
    
    return offset;
}

int RFIDBasicMsg_read_delimited_from(void *_buffer, struct RFIDBasicMsg *_RFIDBasicMsg, int offset) {
    unsigned long size;
    
    offset = read_raw_varint32(&size, _buffer, offset);
    RFIDBasicMsg_read(_buffer, _RFIDBasicMsg, offset, size + offset);
    
    return offset + size;
}


/*******************************************************************
 * Message: rfid_board_api.proto, line 280
 *******************************************************************/
int RFIDBasicPayloadMsg_write(struct RFIDBasicPayloadMsg *_RFIDBasicPayloadMsg, void *_buffer, int offset) {
    /* Write content of each message element.*/
    offset = write_raw_varint32((1<<3)+0, _buffer, offset);
    offset = write_raw_varint32(_RFIDBasicPayloadMsg->_errorCode, _buffer, offset);

    
    return offset;
}

int RFIDBasicPayloadMsg_write_with_tag(struct RFIDBasicPayloadMsg *_RFIDBasicPayloadMsg, void *_buffer, int offset, int tag) {
    /* Write tag.*/
    offset = write_raw_varint32((tag<<3)+2, _buffer, offset);
    /* Write content.*/
    offset = RFIDBasicPayloadMsg_write_delimited_to(_RFIDBasicPayloadMsg, _buffer, offset);
    
    return offset;
}

int RFIDBasicPayloadMsg_write_delimited_to(struct RFIDBasicPayloadMsg *_RFIDBasicPayloadMsg, void *_buffer, int offset) {
    int i, shift, new_offset, size;
    
    new_offset = RFIDBasicPayloadMsg_write(_RFIDBasicPayloadMsg, _buffer, offset);
    size = new_offset - offset;
    shift = (size > 127) ? 2 : 1;
    for (i = new_offset - 1; i >= offset; -- i)
        *((char *)_buffer + i + shift) = *((char *)_buffer + i);
    
    write_raw_varint32((unsigned long) size, _buffer, offset);         
        
    return new_offset + shift;
}

void RFIDBasicPayloadMsg_clear(struct RFIDBasicPayloadMsg *_RFIDBasicPayloadMsg) {
    _memset(_RFIDBasicPayloadMsg, 0, sizeof(struct RFIDBasicPayloadMsg));
}

int RFIDBasicPayloadMsg_read(void *_buffer, struct RFIDBasicPayloadMsg *_RFIDBasicPayloadMsg, int offset, int limit) {
    int i = 0;
    unsigned long tag = i;

    /* Reset all attributes to 0 in advance. */
    RFIDBasicPayloadMsg_clear(_RFIDBasicPayloadMsg);

    /* Read/interpret all attributes from buffer offset until upper limit is reached. */
    while(offset < limit) {
        offset = read_raw_varint32(&tag, _buffer, offset);
        tag = tag>>3;
        switch(tag){
            //tag of: _RFIDBasicPayloadMsg._errorCode 
            case 1 :
                offset = read_raw_varint32(&tag, _buffer, offset);
                _RFIDBasicPayloadMsg->_errorCode = tag;
                break;
        }
    }
    
    return offset;
}

int RFIDBasicPayloadMsg_read_delimited_from(void *_buffer, struct RFIDBasicPayloadMsg *_RFIDBasicPayloadMsg, int offset) {
    unsigned long size;
    
    offset = read_raw_varint32(&size, _buffer, offset);
    RFIDBasicPayloadMsg_read(_buffer, _RFIDBasicPayloadMsg, offset, size + offset);
    
    return offset + size;
}


/*******************************************************************
 * Message: rfid_board_api.proto, line 326
 *******************************************************************/
int RFIDCommTestPayloadMsg_write(struct RFIDCommTestPayloadMsg *_RFIDCommTestPayloadMsg, void *_buffer, int offset) {
    /* Write content of each message element.*/
    offset = write_raw_varint32((1<<3)+0, _buffer, offset);
    offset = write_raw_varint32(_RFIDCommTestPayloadMsg->_errorCode, _buffer, offset);

    offset = write_raw_varint32((2<<3)+0, _buffer, offset);
    offset = write_raw_varint32(_RFIDCommTestPayloadMsg->_payload, _buffer, offset);

    
    return offset;
}

int RFIDCommTestPayloadMsg_write_with_tag(struct RFIDCommTestPayloadMsg *_RFIDCommTestPayloadMsg, void *_buffer, int offset, int tag) {
    /* Write tag.*/
    offset = write_raw_varint32((tag<<3)+2, _buffer, offset);
    /* Write content.*/
    offset = RFIDCommTestPayloadMsg_write_delimited_to(_RFIDCommTestPayloadMsg, _buffer, offset);
    
    return offset;
}

int RFIDCommTestPayloadMsg_write_delimited_to(struct RFIDCommTestPayloadMsg *_RFIDCommTestPayloadMsg, void *_buffer, int offset) {
    int i, shift, new_offset, size;
    
    new_offset = RFIDCommTestPayloadMsg_write(_RFIDCommTestPayloadMsg, _buffer, offset);
    size = new_offset - offset;
    shift = (size > 127) ? 2 : 1;
    for (i = new_offset - 1; i >= offset; -- i)
        *((char *)_buffer + i + shift) = *((char *)_buffer + i);
    
    write_raw_varint32((unsigned long) size, _buffer, offset);         
        
    return new_offset + shift;
}

void RFIDCommTestPayloadMsg_clear(struct RFIDCommTestPayloadMsg *_RFIDCommTestPayloadMsg) {
    _memset(_RFIDCommTestPayloadMsg, 0, sizeof(struct RFIDCommTestPayloadMsg));
}

int RFIDCommTestPayloadMsg_read(void *_buffer, struct RFIDCommTestPayloadMsg *_RFIDCommTestPayloadMsg, int offset, int limit) {
    int i = 0;
    unsigned long tag = i;

    /* Reset all attributes to 0 in advance. */
    RFIDCommTestPayloadMsg_clear(_RFIDCommTestPayloadMsg);

    /* Read/interpret all attributes from buffer offset until upper limit is reached. */
    while(offset < limit) {
        offset = read_raw_varint32(&tag, _buffer, offset);
        tag = tag>>3;
        switch(tag){
            //tag of: _RFIDCommTestPayloadMsg._errorCode 
            case 1 :
                offset = read_raw_varint32(&tag, _buffer, offset);
                _RFIDCommTestPayloadMsg->_errorCode = tag;
                break;
            //tag of: _RFIDCommTestPayloadMsg._payload 
            case 2 :
                offset = read_raw_varint32(&tag, _buffer, offset);
                _RFIDCommTestPayloadMsg->_payload = tag;
                break;
        }
    }
    
    return offset;
}

int RFIDCommTestPayloadMsg_read_delimited_from(void *_buffer, struct RFIDCommTestPayloadMsg *_RFIDCommTestPayloadMsg, int offset) {
    unsigned long size;
    
    offset = read_raw_varint32(&size, _buffer, offset);
    RFIDCommTestPayloadMsg_read(_buffer, _RFIDCommTestPayloadMsg, offset, size + offset);
    
    return offset + size;
}


/*******************************************************************
 * Message: rfid_board_api.proto, line 350
 *******************************************************************/
int RFIDFieldStatePayloadMsg_write(struct RFIDFieldStatePayloadMsg *_RFIDFieldStatePayloadMsg, void *_buffer, int offset) {
    /* Write content of each message element.*/
    offset = write_raw_varint32((1<<3)+0, _buffer, offset);
    offset = write_raw_varint32(_RFIDFieldStatePayloadMsg->_errorCode, _buffer, offset);

    offset = RFIDFieldState_write_with_tag(&_RFIDFieldStatePayloadMsg->_fieldState, _buffer, offset, 2);
    
    return offset;
}

int RFIDFieldStatePayloadMsg_write_with_tag(struct RFIDFieldStatePayloadMsg *_RFIDFieldStatePayloadMsg, void *_buffer, int offset, int tag) {
    /* Write tag.*/
    offset = write_raw_varint32((tag<<3)+2, _buffer, offset);
    /* Write content.*/
    offset = RFIDFieldStatePayloadMsg_write_delimited_to(_RFIDFieldStatePayloadMsg, _buffer, offset);
    
    return offset;
}

int RFIDFieldStatePayloadMsg_write_delimited_to(struct RFIDFieldStatePayloadMsg *_RFIDFieldStatePayloadMsg, void *_buffer, int offset) {
    int i, shift, new_offset, size;
    
    new_offset = RFIDFieldStatePayloadMsg_write(_RFIDFieldStatePayloadMsg, _buffer, offset);
    size = new_offset - offset;
    shift = (size > 127) ? 2 : 1;
    for (i = new_offset - 1; i >= offset; -- i)
        *((char *)_buffer + i + shift) = *((char *)_buffer + i);
    
    write_raw_varint32((unsigned long) size, _buffer, offset);         
        
    return new_offset + shift;
}

void RFIDFieldStatePayloadMsg_clear(struct RFIDFieldStatePayloadMsg *_RFIDFieldStatePayloadMsg) {
    _memset(_RFIDFieldStatePayloadMsg, 0, sizeof(struct RFIDFieldStatePayloadMsg));
}

int RFIDFieldStatePayloadMsg_read(void *_buffer, struct RFIDFieldStatePayloadMsg *_RFIDFieldStatePayloadMsg, int offset, int limit) {
    int i = 0;
    unsigned long tag = i;

    /* Reset all attributes to 0 in advance. */
    RFIDFieldStatePayloadMsg_clear(_RFIDFieldStatePayloadMsg);

    /* Read/interpret all attributes from buffer offset until upper limit is reached. */
    while(offset < limit) {
        offset = read_raw_varint32(&tag, _buffer, offset);
        tag = tag>>3;
        switch(tag){
            //tag of: _RFIDFieldStatePayloadMsg._errorCode 
            case 1 :
                offset = read_raw_varint32(&tag, _buffer, offset);
                _RFIDFieldStatePayloadMsg->_errorCode = tag;
                break;
            //tag of: _RFIDFieldStatePayloadMsg._fieldState 
            case 2 :
                offset = read_raw_varint32(&tag, _buffer, offset);
                _RFIDFieldStatePayloadMsg->_fieldState = tag;
                break;
        }
    }
    
    return offset;
}

int RFIDFieldStatePayloadMsg_read_delimited_from(void *_buffer, struct RFIDFieldStatePayloadMsg *_RFIDFieldStatePayloadMsg, int offset) {
    unsigned long size;
    
    offset = read_raw_varint32(&size, _buffer, offset);
    RFIDFieldStatePayloadMsg_read(_buffer, _RFIDFieldStatePayloadMsg, offset, size + offset);
    
    return offset + size;
}
