/*****************************************************************************
* Model: I2C1DevMgr.qm
* File:  ./I2C1DevMgr_gen.c
*
* This code has been generated by QM tool (see state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*****************************************************************************/
/*${.::I2C1DevMgr_gen.c} ...................................................*/
/**
 * @file    I2C1DevMgr.c
 * @brief   Declarations for functions for the I2C1DevMgr AO.
 * This state machine handles any device that is attached to the I2C1 bus.
 * This AO doesn't handle the low level I2C commands and instead communicates
 * with I2CBusMgr AO to send the events that kick off the low level I2C cmds.
 * The rationale behind this is that different I2C devices require different
 * I2C commands in different order.  Some EEPROMs request 2 Start bits, some
 * other devices have different timeouts for their write/read commands. This
 * way, the I2C bus logic can stay common and any device differences are
 * handled in the device specific AOs.
 *
 * @note 1: If editing this file, please make sure to update the I2C1DevMgr.qm
 * model.  The generated code from that model should be very similar to the
 * code in this file.
 *
 * @date    10/24/2014
 * @author  Harry Rostovtsev
 * @email   harry_rostovtsev@datacard.com
 * Copyright (C) 2014 Datacard. All rights reserved.
 *
 * @addtogroup groupI2C
 * @{
 */

/* Includes ------------------------------------------------------------------*/
#include "I2C1DevMgr.h"
#include "project_includes.h"           /* Includes common to entire project. */
#include "bsp_defs.h"     /* For seconds to bsp tick conversion (SEC_TO_TICK) */
#include "i2c.h"                                  /* For I2C bus declarations */
#include "i2c_dev.h"                           /* For I2C device declarations */
#include "I2CBusMgr.h"
#if CPLR_APP
#include "cplr.h"
#elif CPLR_BOOT

#else
    #error "Invalid build.  CPLR_APP or CPLR_BOOT must be specified"
#endif

/* Compile-time called macros ------------------------------------------------*/
Q_DEFINE_THIS_FILE                  /* For QSPY to know the name of this file */
DBG_DEFINE_THIS_MODULE( DBG_MODL_I2C_DEV ); /* For debug system to ID this module */

/* Private typedefs ----------------------------------------------------------*/

/**
 * @brief I2C1DevMgr Active Object (AO) "class" that manages the all the I2C
 * devices on the I2C1 Bus.
 * This AO manages the devices connected to the I2C1 bus and all events a
 * ssociated with those devices. It deesn't access to the I2C1 bus directly and
 * instead communicates with the I2CBusMgr AO to request and monitor the direct
 * I2C commands that need to be sent down that are specific for the device that
 * is currently being handled.  See I2CDevMgr.qm for diagram and model.
 */
/*${AOs::I2C1DevMgr} .......................................................*/
typedef struct {
/* protected: */
    QActive super;

    /**< Native QF queue for deferred request events. */
    QEQueue deferredEvtQueue;

    /**< Storage for deferred event queue. */
    QTimeEvt const * deferredEvtQSto[100];

    /**< Specifies which I2CBus1 device is currently being handled by this AO.
     * This should be set when a new I2C_READ_START or I2C_WRITE_START events come
     * in.  Those events should contain the device for which they are meant for. */
    DC3I2CDevice_t iDev;

    /**< Which I2C bus this AO is responsible for.  This variable is set on
         startup and is used to index into the structure that holds all the
         I2C bus settings. */
    I2C_Bus_t iBus;

    /**< QPC timer Used to timeout overall I2C device interactions. */
    QTimeEvt i2cTimerEvt;

    /**< QPC timer Used to timeout discrete I2C bus requests to the I2C1DevMgr AO. */
    QTimeEvt i2cOpTimerEvt;

    /**< Total number of bytes to be read or written with an operation */
    uint16_t bytesTotal;

    /**< Keep track of the starting internal memory address of a read or a
     write operation */
    uint16_t addrStart;

    /**< Number of bytes the "address" variables are */
    uint8_t addrSize;

    /**< Keep track of the last memory location accessed.  This is for R/W operations
     * that don't fit into a single bus request */
    uint16_t addrCurr;

    /**< Keep track of last error that occurs. */
    DC3Error_t errorCode;

    /**< Keep track of whether a read, write or other was requested */
    I2C_Operation_t i2cDevOp;

    /**< QPC timer Used to time post EEPROM writes. */
    QTimeEvt i2cWriteTimerEvt;

    /**< Buffer that holds the data for reads and writes.  It's set to a larger of the
     * I2C sizes since reads can be large while the writes have to be broken into
     * page sized chunks. */
    uint8_t dataBuf[MAX_I2C_READ_LEN];

    /**< Specifies whether the request came from FreeRTOS thread or another AO.  This
         variable keeps track of whether the response needs to get added to the raw
         queue used to communicate with the FreeRTOS thread. */
    AccessType_t accessType;

    /**< Keep track of how many bytes to write on the first page of the device */
    uint8_t writeSizeFirstPage;

    /**< Keep track of how many bytes to write on the last page of the device */
    uint8_t writeSizeLastPage;

    /**< Keep track of how many pages to write to the device */
    uint8_t writeTotalPages;

    /**< Keep track of current page to write to the device */
    uint8_t writeCurrPage;

    /**< To keep track of how many bytes to write each iteration to the device */
    uint8_t writeSizeCurr;

    /**< Keep track of the current address to write to */
    uint16_t writeMemAddrCurr;

    /**< Keep track of the index into the buffer of data when writing several pages */
    uint8_t writeBufferIndex;

    /**< This is a state machine pointer to an event that will be allocated upon entry
     * into the busy state by the I2C1_DEV_RAW_MEM_READ signal and used to store the read
     * i2c data in ReadMem state.  This allows not having a static buffer hanging around.*/
    I2CReadDoneEvt* i2cReadDoneEvt;

    /**< This is a state machine pointer to an event that will be allocated upon entry
     * into the busy state by the I2C1_DEV_RAW_MEM_WRITE signal and used to send a done
     * from the exit of Busy state regardless of operation's success or failure. */
    I2CWriteDoneEvt* i2cWriteDoneEvt;
} I2C1DevMgr;

/* protected: */
static QState I2C1DevMgr_initial(I2C1DevMgr * const me, QEvt const * const e);

/**
 * @brief This state is a catch-all Active state.
 * If any signals need to be handled that do not cause state transitions and
 * are common to the entire AO, they should be handled here.
 *
 * @param  [in,out] me: Pointer to the state machine
 * @param  [in,out] e:  Pointer to the event being processed.
 * @return status_: QState type that specifies where the state
 * machine is going next.
 */
static QState I2C1DevMgr_Active(I2C1DevMgr * const me, QEvt const * const e);

/**
 * @brief   This state indicates that the I2C is currently busy and cannot
 * process incoming data; incoming events will be deferred in this state and
 * handled once the AO goes back to Idle state.
 *
 * @param  [in,out] me: Pointer to the state machine
 * @param  [in,out] e:  Pointer to the event being processed.
 * @return status: QState type that specifies where the state
 * machine is going next.
 */
static QState I2C1DevMgr_Busy(I2C1DevMgr * const me, QEvt const * const e);

/**
 * @brief   This state sends the start bit on the I2C bus.
 *
 * @param  [in,out] me: Pointer to the state machine
 * @param  [in,out] e:  Pointer to the event being processed.
 * @return status: QState type that specifies where the state
 * machine is going next.
 */
static QState I2C1DevMgr_GenerateStart(I2C1DevMgr * const me, QEvt const * const e);

/**
 * @brief   This state sends an address of the I2C device to select the device and
 * selects the TRANSMITTER mode.
 *
 * @param  [in,out] me: Pointer to the state machine
 * @param  [in,out] e:  Pointer to the event being processed.
 * @return status: QState type that specifies where the state
 * machine is going next.
 */
static QState I2C1DevMgr_Send7BitAddrTxMode(I2C1DevMgr * const me, QEvt const * const e);

/**
 * @brief   This state sends the internal memory address of the selected I2C device
 * that tells the device where the read or write will happen.
 *
 * @param  [in,out] me: Pointer to the state machine
 * @param  [in,out] e:  Pointer to the event being processed.
 * @return status: QState type that specifies where the state
 * machine is going next.
 */
static QState I2C1DevMgr_SendInternalAddr(I2C1DevMgr * const me, QEvt const * const e);

/**
 * @brief   This state sends the start bit on the I2C bus.
 * Some I2C devices require a second start bit to do random addr operations.
 *
 * @param  [in,out] me: Pointer to the state machine
 * @param  [in,out] e:  Pointer to the event being processed.
 * @return status: QState type that specifies where the state
 * machine is going next.
 */
static QState I2C1DevMgr_GenerateStart1(I2C1DevMgr * const me, QEvt const * const e);

/**
 * @brief   This state sends an address of the I2C device to select the device and
 * selects the RECEIVER mode.
 *
 * @param  [in,out] me: Pointer to the state machine
 * @param  [in,out] e:  Pointer to the event being processed.
 * @return status: QState type that specifies where the state
 * machine is going next.
 */
static QState I2C1DevMgr_Send7BitAddrRxMode(I2C1DevMgr * const me, QEvt const * const e);

/**
 * @brief   This state sends the command to read to memory in the selected I2C
 * device.
 *
 * @param  [in,out] me: Pointer to the state machine
 * @param  [in,out] e:  Pointer to the event being processed.
 * @return status: QState type that specifies where the state
 * machine is going next.
 */
static QState I2C1DevMgr_ReadMem(I2C1DevMgr * const me, QEvt const * const e);

/**
 * @brief   This state sends the command to write to memory in the selected I2C
 * device.
 *
 * @param  [in,out] me: Pointer to the state machine
 * @param  [in,out] e:  Pointer to the event being processed.
 * @return status: QState type that specifies where the state
 * machine is going next.
 */
static QState I2C1DevMgr_WriteMem(I2C1DevMgr * const me, QEvt const * const e);

/**
 * @brief   This state waits for 5 ms for a post write timeout that I2C devices
 * require after writing a page.
 *
 * @param  [in,out] me: Pointer to the state machine
 * @param  [in,out] e:  Pointer to the event being processed.
 * @return status: QState type that specifies where the state
 * machine is going next.
 */
static QState I2C1DevMgr_PostWriteWait(I2C1DevMgr * const me, QEvt const * const e);

/**
 * @brief   This state checks the I2C bus and makes sure it's not busy.
 *
 * @param  [in,out] me: Pointer to the state machine
 * @param  [in,out] e:  Pointer to the event being processed.
 * @return status: QState type that specifies where the state
 * machine is going next.
 */
static QState I2C1DevMgr_CheckingBus(I2C1DevMgr * const me, QEvt const * const e);

/**
 * @brief   This state checks passed in parameters to the AO and makes sure that
 * nothing dangerous is being requested, such as writes over memory boundaries or
 * buffer overflows.
 *
 * @param  [in,out] me: Pointer to the state machine
 * @param  [in,out] e:  Pointer to the event being processed.
 * @return status: QState type that specifies where the state
 * machine is going next.
 */
static QState I2C1DevMgr_ValidateRequest(I2C1DevMgr * const me, QEvt const * const e);

/**
 * @brief This state indicates that the I2C bus is currently idle and the
 * incoming msg can be handled.
 * This state is the default rest state of the state machine and can handle
 * various I2C requests.  Upon entry, it also checks the deferred queue to see
 * if any request events are waiting which were posted while I2C bus was busy.
 * if there are any waiting, it will read them out, which automatically posts
 * them and the state machine will go and handle them.
 *
 * @param  [in,out] me: Pointer to the state machine
 * @param  [in,out] e:  Pointer to the event being processed.
 * @return status: QState type that specifies where the state
 * machine is going next.
 */
static QState I2C1DevMgr_Idle(I2C1DevMgr * const me, QEvt const * const e);


/* Private defines -----------------------------------------------------------*/
/* Private macros ------------------------------------------------------------*/
/* Private variables and Local objects ---------------------------------------*/
static I2C1DevMgr l_I2C1DevMgr;   /* the single instance of the active object */

/* Global-scope objects ----------))------------------------------------------*/
QActive * const AO_I2C1DevMgr = (QActive *)&l_I2C1DevMgr;/**< "opaque" AO pointer */

/* Private function prototypes -----------------------------------------------*/
/* Private functions ---------------------------------------------------------*/

/**
 * @brief C "constructor" for I2C1DevMgr "class".
 * Initializes all the timers and queues used by the AO, sets up a deferral
 * queue, and sets of the first state.
 * @param [in]: none.
 * @retval: none
 */
/*${AOs::I2C1DevMgr_ctor} ..................................................*/
void I2C1DevMgr_ctor(void) {
    I2C1DevMgr *me = &l_I2C1DevMgr;

    QActive_ctor( &me->super, (QStateHandler)&I2C1DevMgr_initial );
    QTimeEvt_ctor( &me->i2cTimerEvt, I2C1_DEV_TIMEOUT_SIG );
    QTimeEvt_ctor( &me->i2cOpTimerEvt, I2C1_DEV_OP_TIMEOUT_SIG );
    QTimeEvt_ctor( &me->i2cWriteTimerEvt, I2C1_DEV_POST_WRITE_TIMER_SIG );

    /* Initialize the deferred event queue and storage for it */
    QEQueue_init(
        &me->deferredEvtQueue,
        (QEvt const **)( me->deferredEvtQSto ),
        Q_DIM(me->deferredEvtQSto)
    );

    dbg_slow_printf("Constructor\n");
}

/**
 * @brief I2C1DevMgr Active Object (AO) "class" that manages the all the I2C
 * devices on the I2C1 Bus.
 * This AO manages the devices connected to the I2C1 bus and all events a
 * ssociated with those devices. It deesn't access to the I2C1 bus directly and
 * instead communicates with the I2CBusMgr AO to request and monitor the direct
 * I2C commands that need to be sent down that are specific for the device that
 * is currently being handled.  See I2CDevMgr.qm for diagram and model.
 */
/*${AOs::I2C1DevMgr} .......................................................*/
/*${AOs::I2C1DevMgr::SM} ...................................................*/
static QState I2C1DevMgr_initial(I2C1DevMgr * const me, QEvt const * const e) {
    /* ${AOs::I2C1DevMgr::SM::initial} */
    (void)e;        /* suppress the compiler warning about unused parameter */

    me->iBus = I2CBus1;          /* This AO only handles devices on I2CBus1 */

    QS_OBJ_DICTIONARY(&l_I2C1DevMgr);
    QS_FUN_DICTIONARY(&QHsm_top);
    QS_FUN_DICTIONARY(&I2C1DevMgr_initial);
    QS_FUN_DICTIONARY(&I2C1DevMgr_Active);
    QS_FUN_DICTIONARY(&I2C1DevMgr_Idle);

    QActive_subscribe((QActive *)me, I2C1_DEV_RAW_MEM_WRITE_SIG);
    QActive_subscribe((QActive *)me, I2C1_DEV_RAW_MEM_READ_SIG);

    me->accessType = ACCESS_QPC; /* Init to safe value */
    return Q_TRAN(&I2C1DevMgr_Idle);
}

/**
 * @brief This state is a catch-all Active state.
 * If any signals need to be handled that do not cause state transitions and
 * are common to the entire AO, they should be handled here.
 *
 * @param  [in,out] me: Pointer to the state machine
 * @param  [in,out] e:  Pointer to the event being processed.
 * @return status_: QState type that specifies where the state
 * machine is going next.
 */
/*${AOs::I2C1DevMgr::SM::Active} ...........................................*/
static QState I2C1DevMgr_Active(I2C1DevMgr * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /* ${AOs::I2C1DevMgr::SM::Active} */
        case Q_ENTRY_SIG: {
            /* Post and disarm all the timer events so they can be rearmed at any time */
            QTimeEvt_postIn(
                &me->i2cTimerEvt,
                (QActive *)me,
                SEC_TO_TICKS( HL_MAX_TOUT_SEC_I2C_EV5 )
            );
            QTimeEvt_disarm(&me->i2cTimerEvt);

            QTimeEvt_postIn(
                &me->i2cOpTimerEvt,
                (QActive *)me,
                SEC_TO_TICKS( HL_MAX_TOUT_SEC_I2C_EV5 )
            );
            QTimeEvt_disarm(&me->i2cOpTimerEvt);

            QTimeEvt_postIn(
                &me->i2cWriteTimerEvt,
                (QActive *)me,
                SEC_TO_TICKS( HL_MAX_TOUT_SEC_I2C_EV5 )
            );
            QTimeEvt_disarm(&me->i2cWriteTimerEvt);
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

/**
 * @brief   This state indicates that the I2C is currently busy and cannot
 * process incoming data; incoming events will be deferred in this state and
 * handled once the AO goes back to Idle state.
 *
 * @param  [in,out] me: Pointer to the state machine
 * @param  [in,out] e:  Pointer to the event being processed.
 * @return status: QState type that specifies where the state
 * machine is going next.
 */
/*${AOs::I2C1DevMgr::SM::Active::Busy} .....................................*/
static QState I2C1DevMgr_Busy(I2C1DevMgr * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /* ${AOs::I2C1DevMgr::SM::Active::Busy} */
        case Q_ENTRY_SIG: {
            /* Post a timer on entry */
            QTimeEvt_rearm(
                &me->i2cTimerEvt,
                SEC_TO_TICKS( HL_MAX_TOUT_SEC_I2C_DEV_REQ )
            );
            status_ = Q_HANDLED();
            break;
        }
        /* ${AOs::I2C1DevMgr::SM::Active::Busy} */
        case Q_EXIT_SIG: {
            QTimeEvt_disarm( &me->i2cTimerEvt ); /* Disarm timer on exit */

            LOG_printf( "Finished %s op on dev %s on I2CBus%d to at addr 0x%02x via Acc: %d\n",
                I2C_opToStr( me->i2cDevOp ), I2C_devToStr(me->iDev), me->iDev+1, me->addrStart, me->accessType );

            if ( I2C_OP_MEM_READ == me->i2cDevOp || I2C_OP_REG_READ == me->i2cDevOp ) {
                /* Change only the fields that could have changed since */
                me->i2cReadDoneEvt->status = me->errorCode;

                if ( ACCESS_FREERTOS == me->accessType ) {
            #if CPLR_APP
                    /* Post directly to the "raw" queue for FreeRTOS task to read */
                    QEQueue_postFIFO(&CPLR_evtQueue, (QEvt *)me->i2cReadDoneEvt);
                    vTaskResume( xHandle_CPLR );
            #elif CPLR_BOOT
                    /* Publish the event so other AOs can get it if they want */
                    QF_PUBLISH((QEvt *)me->i2cReadDoneEvt, AO_I2C1DevMgr);
            #else
                #error "Invalid build.  CPLR_APP or CPLR_BOOT must be specified"
            #endif
                } else {
                    /* Publish the event so other AOs can get it if they want */
                    QF_PUBLISH((QEvt *)me->i2cReadDoneEvt, AO_I2C1DevMgr);
                }
            } else if ( I2C_OP_MEM_WRITE == me->i2cDevOp || I2C_OP_REG_WRITE == me->i2cDevOp ) {
                /* Change only the fields that could have changed since */
                me->i2cWriteDoneEvt->status = me->errorCode;

                if ( ACCESS_FREERTOS == me->accessType ) {
            #if CPLR_APP
                    /* Post directly to the "raw" queue for FreeRTOS task to read */
                    QEQueue_postFIFO(&CPLR_evtQueue, (QEvt *)me->i2cWriteDoneEvt);
                    vTaskResume( xHandle_CPLR );
            #elif CPLR_BOOT
                    /* Publish the event so other AOs can get it if they want */
                    QF_PUBLISH((QEvt *)me->i2cWriteDoneEvt, AO_I2C1DevMgr);
            #else
            #error "Invalid build.  CPLR_APP or CPLR_BOOT must be specified"
            #endif
                } else {
                    /* Publish the event so other AOs can get it if they want */
                    QF_PUBLISH((QEvt *)me->i2cWriteDoneEvt, AO_I2C1DevMgr);
                }
            } else {
                WRN_printf("Invalid I2C operation (%d) was somehow specified. Internal error. Ignoring\n", me->i2cDevOp );
            }
            status_ = Q_HANDLED();
            break;
        }
        /* ${AOs::I2C1DevMgr::SM::Active::Busy::I2C1_DEV_TIMEOUT} */
        case I2C1_DEV_TIMEOUT_SIG: {
            ERR_printf("I2C1Dev timeout occurred with error: 0x%08x\n", me->errorCode);
            status_ = Q_TRAN(&I2C1DevMgr_Idle);
            break;
        }
        /* ${AOs::I2C1DevMgr::SM::Active::Busy::I2C1_DEV_RAW_MEM~} */
        case I2C1_DEV_RAW_MEM_READ_SIG: /* intentionally fall through */
        case I2C1_DEV_RAW_MEM_WRITE_SIG: {
            if (QEQueue_getNFree(&me->deferredEvtQueue) > 0) {
               /* defer the request - this event will be handled
                * when the state machine goes back to Idle state */
               QActive_defer((QActive *)me, &me->deferredEvtQueue, e);
               DBG_printf("Deferring I2C request until current is done\n");
            } else {
               /* notify the request sender that the request was ignored.. */
               ERR_printf("Unable to defer I2C request\n");
            }
            status_ = Q_HANDLED();
            break;
        }
        /* ${AOs::I2C1DevMgr::SM::Active::Busy::I2C1_DEV_OP_TIME~} */
        case I2C1_DEV_OP_TIMEOUT_SIG: {
            ERR_printf("I2C1Dev Op timeout occurred with error: 0x%08x\n", me->errorCode);
            status_ = Q_TRAN(&I2C1DevMgr_Idle);
            break;
        }
        default: {
            status_ = Q_SUPER(&I2C1DevMgr_Active);
            break;
        }
    }
    return status_;
}

/**
 * @brief   This state sends the start bit on the I2C bus.
 *
 * @param  [in,out] me: Pointer to the state machine
 * @param  [in,out] e:  Pointer to the event being processed.
 * @return status: QState type that specifies where the state
 * machine is going next.
 */
/*${AOs::I2C1DevMgr::SM::Active::Busy::GenerateStart} ......................*/
static QState I2C1DevMgr_GenerateStart(I2C1DevMgr * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /* ${AOs::I2C1DevMgr::SM::Active::Busy::GenerateStart} */
        case Q_ENTRY_SIG: {
            /* Set error code */
            me->errorCode = ERR_I2C1DEV_EV5_TIMEOUT;

            /* Set timer */
            QTimeEvt_rearm(
                &me->i2cOpTimerEvt,
                SEC_TO_TICKS( HL_MAX_TOUT_SEC_I2C_EV5 )
            );

            /* Directly post an event to the appropriate I2CBusMgr AO */
            static QEvt const qEvt = { I2C_BUS_START_BIT_SIG, 0U, 0U };
            QACTIVE_POST(AO_I2CBusMgr[me->iBus], &qEvt, me);
            status_ = Q_HANDLED();
            break;
        }
        /* ${AOs::I2C1DevMgr::SM::Active::Busy::GenerateStart} */
        case Q_EXIT_SIG: {
            QTimeEvt_disarm(&me->i2cOpTimerEvt);
            status_ = Q_HANDLED();
            break;
        }
        /* ${AOs::I2C1DevMgr::SM::Active::Busy::GenerateStart::I2C_BUS_DONE} */
        case I2C_BUS_DONE_SIG: {
            /* Remember the result of each event coming back from I2CBusMgr AO */
            me->errorCode = ((I2CStatusEvt const *)e)->errorCode;
            /* ${AOs::I2C1DevMgr::SM::Active::Busy::GenerateStart::I2C_BUS_DONE::[NoErr?]} */
            if (ERR_NONE == ((I2CStatusEvt const *)e)->errorCode) {
                status_ = Q_TRAN(&I2C1DevMgr_Send7BitAddrTxMode);
            }
            /* ${AOs::I2C1DevMgr::SM::Active::Busy::GenerateStart::I2C_BUS_DONE::[else]} */
            else {
                status_ = Q_TRAN(&I2C1DevMgr_Idle);
            }
            break;
        }
        default: {
            status_ = Q_SUPER(&I2C1DevMgr_Busy);
            break;
        }
    }
    return status_;
}

/**
 * @brief   This state sends an address of the I2C device to select the device and
 * selects the TRANSMITTER mode.
 *
 * @param  [in,out] me: Pointer to the state machine
 * @param  [in,out] e:  Pointer to the event being processed.
 * @return status: QState type that specifies where the state
 * machine is going next.
 */
/*${AOs::I2C1DevMgr::SM::Active::Busy::Send7BitAddrTxMo~} ..................*/
static QState I2C1DevMgr_Send7BitAddrTxMode(I2C1DevMgr * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /* ${AOs::I2C1DevMgr::SM::Active::Busy::Send7BitAddrTxMo~} */
        case Q_ENTRY_SIG: {
            /* Set error code */
            me->errorCode = ERR_I2C1DEV_EV6_TIMEOUT;

            /* Set timer */
            QTimeEvt_rearm(
                &me->i2cOpTimerEvt,
                SEC_TO_TICKS( HL_MAX_TOUT_SEC_I2C_EV6 )
            );

            /* Allocate and directly post an event to the appropriate I2CBusMgr AO */
            I2CAddrEvt *i2cAddrEvt   = Q_NEW( I2CAddrEvt, I2C_BUS_SEND_7BIT_ADDR_SIG );
            i2cAddrEvt->i2cBus       = me->iBus;
            i2cAddrEvt->addr         = I2C_getDevAddr(me->iDev);
            i2cAddrEvt->addrSize     = I2C_getDevAddrSize(me->iDev);
            i2cAddrEvt->i2cDirection = I2C_Direction_Transmitter;
            QACTIVE_POST(AO_I2CBusMgr[me->iBus], (QEvt *)i2cAddrEvt, me);
            status_ = Q_HANDLED();
            break;
        }
        /* ${AOs::I2C1DevMgr::SM::Active::Busy::Send7BitAddrTxMo~} */
        case Q_EXIT_SIG: {
            QTimeEvt_disarm(&me->i2cOpTimerEvt);
            status_ = Q_HANDLED();
            break;
        }
        /* ${AOs::I2C1DevMgr::SM::Active::Busy::Send7BitAddrTxMo~::I2C_BUS_DONE} */
        case I2C_BUS_DONE_SIG: {
            /* Remember the result of each event coming back from I2CBusMgr AO */
            me->errorCode = ((I2CStatusEvt const *)e)->errorCode;
            /* ${AOs::I2C1DevMgr::SM::Active::Busy::Send7BitAddrTxMo~::I2C_BUS_DONE::[NoErr?]} */
            if (ERR_NONE == ((I2CStatusEvt const *)e)->errorCode) {
                status_ = Q_TRAN(&I2C1DevMgr_SendInternalAddr);
            }
            /* ${AOs::I2C1DevMgr::SM::Active::Busy::Send7BitAddrTxMo~::I2C_BUS_DONE::[else]} */
            else {
                status_ = Q_TRAN(&I2C1DevMgr_Idle);
            }
            break;
        }
        default: {
            status_ = Q_SUPER(&I2C1DevMgr_Busy);
            break;
        }
    }
    return status_;
}

/**
 * @brief   This state sends the internal memory address of the selected I2C device
 * that tells the device where the read or write will happen.
 *
 * @param  [in,out] me: Pointer to the state machine
 * @param  [in,out] e:  Pointer to the event being processed.
 * @return status: QState type that specifies where the state
 * machine is going next.
 */
/*${AOs::I2C1DevMgr::SM::Active::Busy::SendInternalAddr} ...................*/
static QState I2C1DevMgr_SendInternalAddr(I2C1DevMgr * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /* ${AOs::I2C1DevMgr::SM::Active::Busy::SendInternalAddr} */
        case Q_ENTRY_SIG: {
            /* Set error code */
            me->errorCode = ERR_I2C1DEV_EV8_TIMEOUT;

            /* Set timer */
            QTimeEvt_rearm(
                &me->i2cOpTimerEvt,
                SEC_TO_TICKS( HL_MAX_TOUT_SEC_I2C_EV8 )
            );

            /* Allocate and directly post an event to the appropriate I2CBusMgr AO */
            I2CAddrEvt *i2cAddrEvt   = Q_NEW( I2CAddrEvt, I2C_BUS_SEND_DEV_ADDR_SIG );
            i2cAddrEvt->i2cBus       = me->iBus;
            i2cAddrEvt->addr         = me->addrStart;
            i2cAddrEvt->addrSize     = I2C_getMemAddrSize(me->iDev);
            i2cAddrEvt->i2cDirection = I2C_Direction_Transmitter;
            QACTIVE_POST(AO_I2CBusMgr[me->iBus], (QEvt *)i2cAddrEvt, me);
            status_ = Q_HANDLED();
            break;
        }
        /* ${AOs::I2C1DevMgr::SM::Active::Busy::SendInternalAddr} */
        case Q_EXIT_SIG: {
            QTimeEvt_disarm(&me->i2cOpTimerEvt);
            status_ = Q_HANDLED();
            break;
        }
        /* ${AOs::I2C1DevMgr::SM::Active::Busy::SendInternalAddr::I2C_BUS_DONE} */
        case I2C_BUS_DONE_SIG: {
            /* Remember the result of each event coming back from I2CBusMgr AO */
            me->errorCode = ((I2CStatusEvt const *)e)->errorCode;
            /* ${AOs::I2C1DevMgr::SM::Active::Busy::SendInternalAddr::I2C_BUS_DONE::[NoErr?]} */
            if (ERR_NONE == ((I2CStatusEvt const *)e)->errorCode) {
                /* ${AOs::I2C1DevMgr::SM::Active::Busy::SendInternalAddr::I2C_BUS_DONE::[NoErr?]::[Read?]} */
                if (I2C_OP_MEM_READ == me->i2cDevOp || I2C_OP_REG_READ == me->i2cDevOp) {
                    status_ = Q_TRAN(&I2C1DevMgr_GenerateStart1);
                }
                /* ${AOs::I2C1DevMgr::SM::Active::Busy::SendInternalAddr::I2C_BUS_DONE::[NoErr?]::[Write?]} */
                else if (I2C_OP_MEM_WRITE == me->i2cDevOp || I2C_OP_REG_WRITE == me->i2cDevOp) {
                    status_ = Q_TRAN(&I2C1DevMgr_WriteMem);
                }
                else {
                    status_ = Q_UNHANDLED();
                }
            }
            /* ${AOs::I2C1DevMgr::SM::Active::Busy::SendInternalAddr::I2C_BUS_DONE::[else]} */
            else {
                status_ = Q_TRAN(&I2C1DevMgr_Idle);
            }
            break;
        }
        default: {
            status_ = Q_SUPER(&I2C1DevMgr_Busy);
            break;
        }
    }
    return status_;
}

/**
 * @brief   This state sends the start bit on the I2C bus.
 * Some I2C devices require a second start bit to do random addr operations.
 *
 * @param  [in,out] me: Pointer to the state machine
 * @param  [in,out] e:  Pointer to the event being processed.
 * @return status: QState type that specifies where the state
 * machine is going next.
 */
/*${AOs::I2C1DevMgr::SM::Active::Busy::GenerateStart1} .....................*/
static QState I2C1DevMgr_GenerateStart1(I2C1DevMgr * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /* ${AOs::I2C1DevMgr::SM::Active::Busy::GenerateStart1} */
        case Q_ENTRY_SIG: {
            /* Set error code */
            me->errorCode = ERR_I2C1DEV_EV5_TIMEOUT;

            /* Set timer */
            QTimeEvt_rearm(
                &me->i2cOpTimerEvt,
                SEC_TO_TICKS( HL_MAX_TOUT_SEC_I2C_EV5 )
            );

            /* Directly post an event to the appropriate I2CBusMgr AO */
            static QEvt const qEvt = { I2C_BUS_START_BIT_SIG, 0U, 0U };
            QACTIVE_POST(AO_I2CBusMgr[me->iBus], &qEvt, me);
            status_ = Q_HANDLED();
            break;
        }
        /* ${AOs::I2C1DevMgr::SM::Active::Busy::GenerateStart1} */
        case Q_EXIT_SIG: {
            QTimeEvt_disarm(&me->i2cOpTimerEvt);
            status_ = Q_HANDLED();
            break;
        }
        /* ${AOs::I2C1DevMgr::SM::Active::Busy::GenerateStart1::I2C_BUS_DONE} */
        case I2C_BUS_DONE_SIG: {
            /* Remember the result of each event coming back from I2CBusMgr AO */
            me->errorCode = ((I2CStatusEvt const *)e)->errorCode;
            /* ${AOs::I2C1DevMgr::SM::Active::Busy::GenerateStart1::I2C_BUS_DONE::[NoErr?]} */
            if (ERR_NONE == ((I2CStatusEvt const *)e)->errorCode) {
                status_ = Q_TRAN(&I2C1DevMgr_Send7BitAddrRxMode);
            }
            /* ${AOs::I2C1DevMgr::SM::Active::Busy::GenerateStart1::I2C_BUS_DONE::[else]} */
            else {
                status_ = Q_TRAN(&I2C1DevMgr_Idle);
            }
            break;
        }
        default: {
            status_ = Q_SUPER(&I2C1DevMgr_Busy);
            break;
        }
    }
    return status_;
}

/**
 * @brief   This state sends an address of the I2C device to select the device and
 * selects the RECEIVER mode.
 *
 * @param  [in,out] me: Pointer to the state machine
 * @param  [in,out] e:  Pointer to the event being processed.
 * @return status: QState type that specifies where the state
 * machine is going next.
 */
/*${AOs::I2C1DevMgr::SM::Active::Busy::Send7BitAddrRxMo~} ..................*/
static QState I2C1DevMgr_Send7BitAddrRxMode(I2C1DevMgr * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /* ${AOs::I2C1DevMgr::SM::Active::Busy::Send7BitAddrRxMo~} */
        case Q_ENTRY_SIG: {
            /* Set error code */
            me->errorCode = ERR_I2C1DEV_EV6_TIMEOUT;

            /* Set timer */
            QTimeEvt_rearm(
                &me->i2cOpTimerEvt,
                SEC_TO_TICKS( HL_MAX_TOUT_SEC_I2C_EV6 )
            );

            /* Allocate and directly post an event to the appropriate I2CBusMgr AO */
            I2CAddrEvt *i2cAddrEvt   = Q_NEW( I2CAddrEvt, I2C_BUS_SEND_7BIT_ADDR_SIG );
            i2cAddrEvt->i2cBus       = me->iBus;
            i2cAddrEvt->addr         = I2C_getDevAddr(me->iDev);
            i2cAddrEvt->addrSize     = I2C_getDevAddrSize(me->iDev);
            i2cAddrEvt->i2cDirection = I2C_Direction_Receiver;
            QACTIVE_POST(AO_I2CBusMgr[me->iBus], (QEvt *)i2cAddrEvt, me);
            status_ = Q_HANDLED();
            break;
        }
        /* ${AOs::I2C1DevMgr::SM::Active::Busy::Send7BitAddrRxMo~} */
        case Q_EXIT_SIG: {
            QTimeEvt_disarm(&me->i2cOpTimerEvt);
            status_ = Q_HANDLED();
            break;
        }
        /* ${AOs::I2C1DevMgr::SM::Active::Busy::Send7BitAddrRxMo~::I2C_BUS_DONE} */
        case I2C_BUS_DONE_SIG: {
            /* Remember the result of each event coming back from I2CBusMgr AO */
            me->errorCode = ((I2CStatusEvt const *)e)->errorCode;
            /* ${AOs::I2C1DevMgr::SM::Active::Busy::Send7BitAddrRxMo~::I2C_BUS_DONE::[NoErr?]} */
            if (ERR_NONE == ((I2CStatusEvt const *)e)->errorCode) {
                status_ = Q_TRAN(&I2C1DevMgr_ReadMem);
            }
            /* ${AOs::I2C1DevMgr::SM::Active::Busy::Send7BitAddrRxMo~::I2C_BUS_DONE::[else]} */
            else {
                status_ = Q_TRAN(&I2C1DevMgr_Idle);
            }
            break;
        }
        default: {
            status_ = Q_SUPER(&I2C1DevMgr_Busy);
            break;
        }
    }
    return status_;
}

/**
 * @brief   This state sends the command to read to memory in the selected I2C
 * device.
 *
 * @param  [in,out] me: Pointer to the state machine
 * @param  [in,out] e:  Pointer to the event being processed.
 * @return status: QState type that specifies where the state
 * machine is going next.
 */
/*${AOs::I2C1DevMgr::SM::Active::Busy::ReadMem} ............................*/
static QState I2C1DevMgr_ReadMem(I2C1DevMgr * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /* ${AOs::I2C1DevMgr::SM::Active::Busy::ReadMem} */
        case Q_ENTRY_SIG: {
            /* Set error code */
            me->errorCode = ERR_I2C1DEV_READ_MEM_TIMEOUT;

            /* Set timer */
            QTimeEvt_rearm(
                &me->i2cOpTimerEvt,
                SEC_TO_TICKS( HL_MAX_TOUT_SEC_I2C_READ )
            );

            /* Allocate and directly post an event to the appropriate I2CBusMgr AO */
            I2CReadMemReqEvt *i2cReadMemEvt = Q_NEW( I2CReadMemReqEvt, I2C_BUS_READ_MEM_SIG );
            i2cReadMemEvt->i2cBus           = me->iBus;
            i2cReadMemEvt->addr             = me->addrStart;
            i2cReadMemEvt->addrSize         = I2C_getMemAddrSize(me->iDev);
            i2cReadMemEvt->memAccessType    = I2C_MEM_DMA;
            i2cReadMemEvt->bytes            = me->bytesTotal;
            QACTIVE_POST(AO_I2CBusMgr[me->iBus], (QEvt *)i2cReadMemEvt, me);
            status_ = Q_HANDLED();
            break;
        }
        /* ${AOs::I2C1DevMgr::SM::Active::Busy::ReadMem} */
        case Q_EXIT_SIG: {
            QTimeEvt_disarm(&me->i2cOpTimerEvt);
            status_ = Q_HANDLED();
            break;
        }
        /* ${AOs::I2C1DevMgr::SM::Active::Busy::ReadMem::I2C_BUS_DONE} */
        case I2C_BUS_DONE_SIG: {
            /* Remember the result of each event coming back from I2CBusMgr AO */
            me->errorCode = ((I2CStatusEvt const *)e)->errorCode;
            /* ${AOs::I2C1DevMgr::SM::Active::Busy::ReadMem::I2C_BUS_DONE::[NoErr?]} */
            if (ERR_NONE == ((I2CBusDataEvt const *)e)->errorCode) {
                /* Set this so the state machine remembers the result */
                me->errorCode = ERR_NONE;

                //I2CReadDoneEvt *i2cReadDoneEvt = Q_NEW(I2CReadDoneEvt, I2C1_DEV_READ_DONE_SIG);
                me->i2cReadDoneEvt->status = me->errorCode;
                me->i2cReadDoneEvt->i2cDev = me->iDev;

                /* Use the event buffer to convert buffer and print it before using it to send the
                 * response */
                uint16_t tmpLen = 0;
                DC3Error_t err = CON_hexToStr(
                    ((I2CBusDataEvt const *)e)->dataBuf, // data to convert
                    ((I2CBusDataEvt const *)e)->dataLen, // length of data to convert
                    (char *)me->i2cReadDoneEvt->dataBuf, // where to write output
                    sizeof(me->i2cReadDoneEvt->dataBuf), // max size of output buffer
                    &tmpLen,                             // size of the resulting output
                    0,                                   // no columns
                    ' ',                                 // separator
                    true                                 // bPrintX
                );

                if ( ERR_NONE == err ) {
                    LOG_printf( "Read %d bytes: %s\n",
                        ((I2CBusDataEvt const *)e)->dataLen, me->i2cReadDoneEvt->dataBuf );
                } else {
                    WRN_printf( "Read %d bytes but data too big for printing due to buffer size. Not shown\n",
                        ((I2CBusDataEvt const *)e)->dataLen );
                }

                /* Now copy the data from the I2CBus evt to the I2CReadDone evt */
                me->i2cReadDoneEvt->bytes  = ((I2CBusDataEvt const *)e)->dataLen;
                MEMCPY(
                    me->i2cReadDoneEvt->dataBuf,
                    ((I2CBusDataEvt const *)e)->dataBuf,
                    me->i2cReadDoneEvt->bytes
                );
                status_ = Q_TRAN(&I2C1DevMgr_Idle);
            }
            /* ${AOs::I2C1DevMgr::SM::Active::Busy::ReadMem::I2C_BUS_DONE::[else]} */
            else {
                status_ = Q_TRAN(&I2C1DevMgr_Idle);
            }
            break;
        }
        default: {
            status_ = Q_SUPER(&I2C1DevMgr_Busy);
            break;
        }
    }
    return status_;
}

/**
 * @brief   This state sends the command to write to memory in the selected I2C
 * device.
 *
 * @param  [in,out] me: Pointer to the state machine
 * @param  [in,out] e:  Pointer to the event being processed.
 * @return status: QState type that specifies where the state
 * machine is going next.
 */
/*${AOs::I2C1DevMgr::SM::Active::Busy::WriteMem} ...........................*/
static QState I2C1DevMgr_WriteMem(I2C1DevMgr * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /* ${AOs::I2C1DevMgr::SM::Active::Busy::WriteMem} */
        case Q_ENTRY_SIG: {
            /* Set error code */
            me->errorCode = ERR_I2C1DEV_WRITE_MEM_TIMEOUT;

            /* Set timer */
            QTimeEvt_rearm(
                &me->i2cOpTimerEvt,
                SEC_TO_TICKS( HL_MAX_TOUT_SEC_I2C_WRITE )
            );

            /* Allocate and directly post an event to the appropriate I2CBusMgr AO */
            I2CWriteMemReqEvt *i2cWriteMemReqEvt = Q_NEW( I2CWriteMemReqEvt, I2C_BUS_WRITE_MEM_SIG );
            i2cWriteMemReqEvt->i2cBus           = me->iBus;
            i2cWriteMemReqEvt->addr             = me->writeMemAddrCurr;
            i2cWriteMemReqEvt->addrSize         = I2C_getMemAddrSize(me->iDev);
            i2cWriteMemReqEvt->memAccessType    = I2C_MEM_DMA;
            i2cWriteMemReqEvt->bytes            = me->writeSizeCurr;
            MEMCPY(
                i2cWriteMemReqEvt->dataBuf,
                &me->dataBuf[me->writeBufferIndex],
                i2cWriteMemReqEvt->bytes
            );
            QACTIVE_POST(AO_I2CBusMgr[me->iBus], (QEvt *)i2cWriteMemReqEvt, me);
            status_ = Q_HANDLED();
            break;
        }
        /* ${AOs::I2C1DevMgr::SM::Active::Busy::WriteMem} */
        case Q_EXIT_SIG: {
            QTimeEvt_disarm(&me->i2cOpTimerEvt);
            status_ = Q_HANDLED();
            break;
        }
        /* ${AOs::I2C1DevMgr::SM::Active::Busy::WriteMem::I2C_BUS_DONE} */
        case I2C_BUS_DONE_SIG: {
            /* Remember the result of each event coming back from I2CBusMgr AO */
            me->errorCode = ((I2CStatusEvt const *)e)->errorCode;

            /* ${AOs::I2C1DevMgr::SM::Active::Busy::WriteMem::I2C_BUS_DONE::[NoErr?]} */
            if (ERR_NONE == me->errorCode) {
                status_ = Q_TRAN(&I2C1DevMgr_PostWriteWait);
            }
            /* ${AOs::I2C1DevMgr::SM::Active::Busy::WriteMem::I2C_BUS_DONE::[else]} */
            else {
                status_ = Q_TRAN(&I2C1DevMgr_Idle);
            }
            break;
        }
        default: {
            status_ = Q_SUPER(&I2C1DevMgr_Busy);
            break;
        }
    }
    return status_;
}

/**
 * @brief   This state waits for 5 ms for a post write timeout that I2C devices
 * require after writing a page.
 *
 * @param  [in,out] me: Pointer to the state machine
 * @param  [in,out] e:  Pointer to the event being processed.
 * @return status: QState type that specifies where the state
 * machine is going next.
 */
/*${AOs::I2C1DevMgr::SM::Active::Busy::PostWriteWait} ......................*/
static QState I2C1DevMgr_PostWriteWait(I2C1DevMgr * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /* ${AOs::I2C1DevMgr::SM::Active::Busy::PostWriteWait} */
        case Q_ENTRY_SIG: {
            /* Set timer */
            QTimeEvt_rearm(
                &me->i2cWriteTimerEvt,
                MS_TO_TICKS( HL_MAX_TIME_MS_I2C_POST_WRITE )
            );
            status_ = Q_HANDLED();
            break;
        }
        /* ${AOs::I2C1DevMgr::SM::Active::Busy::PostWriteWait} */
        case Q_EXIT_SIG: {
            QTimeEvt_disarm(&me->i2cWriteTimerEvt);
            status_ = Q_HANDLED();
            break;
        }
        /* ${AOs::I2C1DevMgr::SM::Active::Busy::PostWriteWait::I2C1_DEV_POST_WR~} */
        case I2C1_DEV_POST_WRITE_TIMER_SIG: {
            /* Update the counter and index */
            me->writeMemAddrCurr += me->writeSizeCurr;
            me->writeBufferIndex += me->writeSizeCurr;
            me->writeCurrPage    += 1;
            me->addrStart         = me->writeMemAddrCurr;
            /* ${AOs::I2C1DevMgr::SM::Active::Busy::PostWriteWait::I2C1_DEV_POST_WR~::[MorePages?]} */
            if (me->writeCurrPage <= me->writeTotalPages) {
                if ( me->writeCurrPage == me->writeTotalPages && me->writeSizeLastPage != 0 ) {
                    me->writeSizeCurr = me->writeSizeLastPage;
                } else {
                    me->writeSizeCurr = I2C_getPageSize( me->iDev );
                }

                DBG_printf("Writing page %d (%d bytes) out of %d total to addr 0x%02x\n",
                    me->writeCurrPage, me->writeSizeCurr, me->writeTotalPages, me->writeMemAddrCurr);
                status_ = Q_TRAN(&I2C1DevMgr_CheckingBus);
            }
            /* ${AOs::I2C1DevMgr::SM::Active::Busy::PostWriteWait::I2C1_DEV_POST_WR~::[else]} */
            else {
                LOG_printf(
                    "Wrote %d pages to %s. Error: 0x%08x\n",
                    me->writeTotalPages,
                    I2C_devToStr(me->iDev),
                    me->errorCode
                );

                /* Publish event for anyone who is listening */
                //I2CWriteDoneEvt *i2cWriteDoneEvt = Q_NEW(I2CWriteDoneEvt, I2C1_DEV_WRITE_DONE_SIG);
                me->i2cWriteDoneEvt->status = me->errorCode;
                me->i2cWriteDoneEvt->bytes  = me->bytesTotal;
                status_ = Q_TRAN(&I2C1DevMgr_Idle);
            }
            break;
        }
        default: {
            status_ = Q_SUPER(&I2C1DevMgr_Busy);
            break;
        }
    }
    return status_;
}

/**
 * @brief   This state checks the I2C bus and makes sure it's not busy.
 *
 * @param  [in,out] me: Pointer to the state machine
 * @param  [in,out] e:  Pointer to the event being processed.
 * @return status: QState type that specifies where the state
 * machine is going next.
 */
/*${AOs::I2C1DevMgr::SM::Active::Busy::CheckingBus} ........................*/
static QState I2C1DevMgr_CheckingBus(I2C1DevMgr * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /* ${AOs::I2C1DevMgr::SM::Active::Busy::CheckingBus} */
        case Q_ENTRY_SIG: {
            /* Set error code */
            me->errorCode = ERR_I2C1DEV_CHECK_BUS_TIMEOUT;

            /* Set timer */
            QTimeEvt_rearm(
                &me->i2cOpTimerEvt,
                SEC_TO_TICKS( HL_MAX_TOUT_SEC_I2C_BUS_CHECK )
            );

            /* Allocate a dynamic event to send back the result after attempting to recover
             * the I2C bus. */
            I2CAddrEvt *i2cAddrEvt = Q_NEW( I2CAddrEvt, I2C_BUS_CHECK_FREE_SIG );
            i2cAddrEvt->i2cBus     = me->iBus;
            i2cAddrEvt->addr       = I2C_getDevAddr(me->iDev);
            i2cAddrEvt->addrSize   = I2C_getDevAddrSize(me->iDev);
            QACTIVE_POST(AO_I2CBusMgr[me->iBus], (QEvt *)(i2cAddrEvt), me);
            status_ = Q_HANDLED();
            break;
        }
        /* ${AOs::I2C1DevMgr::SM::Active::Busy::CheckingBus} */
        case Q_EXIT_SIG: {
            QTimeEvt_disarm(&me->i2cOpTimerEvt);
            status_ = Q_HANDLED();
            break;
        }
        /* ${AOs::I2C1DevMgr::SM::Active::Busy::CheckingBus::I2C_BUS_DONE} */
        case I2C_BUS_DONE_SIG: {
            /* Remember the result of each event coming back from I2CBusMgr AO */
            me->errorCode = ((I2CStatusEvt const *)e)->errorCode;
            /* ${AOs::I2C1DevMgr::SM::Active::Busy::CheckingBus::I2C_BUS_DONE::[NoErr?]} */
            if (ERR_NONE == me->errorCode) {
                status_ = Q_TRAN(&I2C1DevMgr_GenerateStart);
            }
            /* ${AOs::I2C1DevMgr::SM::Active::Busy::CheckingBus::I2C_BUS_DONE::[else]} */
            else {
                status_ = Q_TRAN(&I2C1DevMgr_Idle);
            }
            break;
        }
        default: {
            status_ = Q_SUPER(&I2C1DevMgr_Busy);
            break;
        }
    }
    return status_;
}

/**
 * @brief   This state checks passed in parameters to the AO and makes sure that
 * nothing dangerous is being requested, such as writes over memory boundaries or
 * buffer overflows.
 *
 * @param  [in,out] me: Pointer to the state machine
 * @param  [in,out] e:  Pointer to the event being processed.
 * @return status: QState type that specifies where the state
 * machine is going next.
 */
/*${AOs::I2C1DevMgr::SM::Active::Busy::ValidateRequest} ....................*/
static QState I2C1DevMgr_ValidateRequest(I2C1DevMgr * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /* ${AOs::I2C1DevMgr::SM::Active::Busy::ValidateRequest} */
        case Q_ENTRY_SIG: {
            /* Set error code to none.  If any of the checks fail, they'll set the error code */
            me->errorCode = ERR_NONE;

            /* no timer needed in this state since there is no waiting on anyone */

            /* Check if the inputs are going to cause any problems. */

            /* Make sure the device requested is valid */
            if ( !IS_I2C_DEVICE(me->iDev) ) {
                me->errorCode = ERR_I2C1DEV_INVALID_DEVICE;
                ERR_printf("Invalid I2C device: %d. Error: 0x%08x\n", me->iDev, me->errorCode);
                goto I2CDEV1_VALIDATE_FINISH_TAG;
            }

            /* Any request for a totalBytes being zero is definitely wrong.  Attempting to read
             * or write 0 bytes will cause problems. */
            if( 0 == me->bytesTotal ) {
                me->errorCode = ERR_I2C1DEV_0_BYTE_REQUEST;
                ERR_printf("%s Request on %s for a 0 byte access. Error: 0x%08x\n",
                    I2C_opToStr( me->i2cDevOp ), I2C_devToStr(me->iDev), me->errorCode);
                goto I2CDEV1_VALIDATE_FINISH_TAG;
            }

            /* Make sure the local buffer is not overflowed by the request */
            if( me->bytesTotal > MAX_I2C_READ_LEN || me->bytesTotal > MAX_I2C_WRITE_LEN) {
                me->errorCode = ERR_I2C1DEV_OVERFLOW_REQUEST;
                ERR_printf(
                    "%s Request on %s for a %d byte access. Max allowed is %d. Error: 0x%08x\n",
                    I2C_opToStr( me->i2cDevOp ), I2C_devToStr(me->iDev), me->bytesTotal,
                    ( I2C_OP_MEM_READ == me->i2cDevOp || I2C_OP_REG_READ == me->i2cDevOp ) ? MAX_I2C_READ_LEN : MAX_I2C_WRITE_LEN,
                    me->errorCode
                );
                goto I2CDEV1_VALIDATE_FINISH_TAG;
            }

            /* Don't allow reads or writes over the end of the device memory since bad things
             * can happen, especially with writes. */
            if( ( me->addrStart + me->bytesTotal ) > I2C_getMaxMemAddr(me->iDev) ) {
                me->errorCode = ERR_I2C1DEV_ACCESS_OVER_END_OF_DEVICE_MEM;
                ERR_printf("%s op for %s access will cross over device mem boundary. Error: 0x%08x\n",
                    I2C_opToStr( me->i2cDevOp ),  I2C_devToStr(me->iDev), 	me->errorCode);
                ERR_printf("Dev min addr: 0x%02x, max addr: 0x%02x, requested start addr: 0x%02x for %d bytes.\n",
                    I2C_getMinMemAddr(me->iDev), I2C_getMaxMemAddr(me->iDev), me->addrStart, me->bytesTotal );
                goto I2CDEV1_VALIDATE_FINISH_TAG;
            }

            switch( me->i2cDevOp ) {
                case I2C_OP_MEM_READ:  /* Read device memory of I2C device */
                    /* Nothing to be done here */
                    break;

                case I2C_OP_MEM_WRITE:  /* Write device memory of I2C device */
                    /* Only allow writes to writable devices */
                    if ( !IS_I2C_DEVICE_RW(me->iDev) ) {
                        me->errorCode = ERR_I2C1DEV_READ_ONLY_DEVICE;
                        ERR_printf("%s op for %s access attempt to write to RO device. Error: 0x%08x\n",
                            I2C_opToStr( me->i2cDevOp ),  I2C_devToStr(me->iDev), me->errorCode);
                        goto I2CDEV1_VALIDATE_FINISH_TAG;
                    }

                    /* Use the state machine buffer to do a print out of the data we are attempting to
                     * write so  we don't have to have a separate buffer just for that. After printing,
                     * the buffer can be used to do its actual purpose of storing data for when a later
                     * state will send it to be written. */

                    /* Figure out the write sizes of pages if number of bytes desired to be written is
                     bigger than the page size. */
                    me->errorCode = I2C_calcPageWriteSizes(
                        &(me->writeSizeFirstPage),
                        &(me->writeSizeLastPage),
                        &(me->writeTotalPages),
                        me->addrStart,
                        me->bytesTotal,
                        I2C_getPageSize( me->iDev )
                    );

                    if( ERR_NONE != me->errorCode ) {
                        ERR_printf("%s op for %s write: unable to calculate page writes. Aborting write. Error: 0x%08x\n",
                            I2C_opToStr( me->i2cDevOp ),  I2C_devToStr(me->iDev), me->errorCode);
                        goto I2CDEV1_VALIDATE_FINISH_TAG;
                    }

                    LOG_printf( "write sizes: 1st page: %d, lst page: %d, tot pages: %d\n",
                        me->writeSizeFirstPage, me->writeSizeLastPage, me->writeTotalPages );

                    /* This is the first iteration through the "loop" which writes several pages */
                    me->writeCurrPage    = 1;
                    me->writeSizeCurr    = me->writeSizeFirstPage;
                    me->writeBufferIndex = 0;
                    me->writeMemAddrCurr = me->addrStart;

                    DBG_printf("Writing page %d (%d bytes) out of %d total to addr 0x%02x\n",
                        me->writeCurrPage, me->writeSizeCurr, me->writeTotalPages, me->writeMemAddrCurr);

                break;

                case I2C_OP_REG_READ:     /* Intentionally fall through */
                case I2C_OP_REG_WRITE:
                    /* TODO: these operations may be needed later if any register based devices
                     * on I2C bus are ever added.  For now, this is an error. */
                    me->errorCode = ERR_UNIMPLEMENTED;
                    ERR_printf("%s op for %s access is currently unimplemented. Error: 0x%08x\n",
                        I2C_opToStr( me->i2cDevOp ),  I2C_devToStr(me->iDev), me->errorCode);
                    goto I2CDEV1_VALIDATE_FINISH_TAG;
                    break;
                default:                 /* Undefined I2C operation. */
                    me->errorCode = ERR_I2C1DEV_INVALID_OPERATION;
                    ERR_printf("%d (Unable to translate to string) op for %s is undefined. Error: 0x%08x\n",
                        me->i2cDevOp,  I2C_devToStr(me->iDev), me->errorCode);
                    goto I2CDEV1_VALIDATE_FINISH_TAG;
                    break;
            }

            /* Tag that can be jumped to if an error is encountered or reached naturally */
            I2CDEV1_VALIDATE_FINISH_TAG:
            ; // workaround for a label can't be a statement due to a comment after the label

            /* Post an event to self to proceed to the next state */
            QEvt *evt = Q_NEW( QEvt, I2C1_DEV_PRIVATE_SIG );
            QACTIVE_POST(AO_I2C1DevMgr, (QEvt *)(evt), me);
            status_ = Q_HANDLED();
            break;
        }
        /* ${AOs::I2C1DevMgr::SM::Active::Busy::ValidateRequest::I2C1_DEV_PRIVATE} */
        case I2C1_DEV_PRIVATE_SIG: {
            /* Internal signal with no data with it.  Just check if checking inputs for I2C req
             * produced an error that was recorded */
            /* ${AOs::I2C1DevMgr::SM::Active::Busy::ValidateRequest::I2C1_DEV_PRIVATE::[NoErr?]} */
            if (ERR_NONE == me->errorCode) {
                status_ = Q_TRAN(&I2C1DevMgr_CheckingBus);
            }
            /* ${AOs::I2C1DevMgr::SM::Active::Busy::ValidateRequest::I2C1_DEV_PRIVATE::[else]} */
            else {
                status_ = Q_TRAN(&I2C1DevMgr_Idle);
            }
            break;
        }
        default: {
            status_ = Q_SUPER(&I2C1DevMgr_Busy);
            break;
        }
    }
    return status_;
}

/**
 * @brief This state indicates that the I2C bus is currently idle and the
 * incoming msg can be handled.
 * This state is the default rest state of the state machine and can handle
 * various I2C requests.  Upon entry, it also checks the deferred queue to see
 * if any request events are waiting which were posted while I2C bus was busy.
 * if there are any waiting, it will read them out, which automatically posts
 * them and the state machine will go and handle them.
 *
 * @param  [in,out] me: Pointer to the state machine
 * @param  [in,out] e:  Pointer to the event being processed.
 * @return status: QState type that specifies where the state
 * machine is going next.
 */
/*${AOs::I2C1DevMgr::SM::Active::Idle} .....................................*/
static QState I2C1DevMgr_Idle(I2C1DevMgr * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /* ${AOs::I2C1DevMgr::SM::Active::Idle} */
        case Q_ENTRY_SIG: {
            /* recall the request from the private requestQueue */
            QActive_recall(
                (QActive *)me,
                &me->deferredEvtQueue
            );

            DBG_printf("Back in Idle state.\n");
            status_ = Q_HANDLED();
            break;
        }
        /* ${AOs::I2C1DevMgr::SM::Active::Idle::I2C1_DEV_RAW_MEM~} */
        case I2C1_DEV_RAW_MEM_READ_SIG: {
            /* Store all the data from the event and look up a few things */

            /* I2C1Dev AO assumes that the addresses that are passed in are already correct
             * for the device they are being sent for.  Most of access happen via the DB
             * which does all the work of figuring out the correct addresses and sizes.  If
             * direct access of I2C1Dev AO is being performed, it's the role of the user to
             * know the correct addresses. */
            me->iDev       = ((I2CReadReqEvt const *)e)->i2cDev;
            me->addrStart  = ((I2CReadReqEvt const *)e)->addr;
            me->accessType = ((I2CReadReqEvt const *)e)->accessType;
            me->bytesTotal = ((I2CReadReqEvt const *)e)->bytes;
            me->addrSize   = I2C_getMemAddrSize(me->iDev);
            me->i2cDevOp   = I2C_OP_MEM_READ;

            LOG_printf( "Trying %s op to read %d bytes from dev %s on I2CBus%d to at addr 0x%02x via Acc: %d\n",
                I2C_opToStr( me->i2cDevOp ), me->bytesTotal, I2C_devToStr(me->iDev), me->iDev+1, me->addrStart, me->accessType );

            /* Allocate a ReadDone evt that will ALWAYS be sent out upon exit of the Busy state
             * for read operations. */
            me->i2cReadDoneEvt = Q_NEW(I2CReadDoneEvt, I2C1_DEV_READ_DONE_SIG);

            /* Fill out the fields that won't change or to just safe values in case of failure */
            me->i2cReadDoneEvt->i2cDev = me->iDev;
            me->i2cReadDoneEvt->bytes  = 0;
            status_ = Q_TRAN(&I2C1DevMgr_ValidateRequest);
            break;
        }
        /* ${AOs::I2C1DevMgr::SM::Active::Idle::I2C1_DEV_RAW_MEM~} */
        case I2C1_DEV_RAW_MEM_WRITE_SIG: {
            /* Store all the data from the event and look up a few things */

            /* I2C1Dev AO assumes that the addresses that are passed in are already correct
             * for the device they are being sent for.  Most of access happen via the DB
             * which does all the work of figuring out the correct addresses and sizes.  If
             * direct access of I2C1Dev AO is being performed, it's the role of the user to
             * know the correct addresses. */
            me->iDev       = ((I2CWriteReqEvt const *)e)->i2cDev;
            me->addrStart  = ((I2CWriteReqEvt const *)e)->addr;
            me->accessType = ((I2CWriteReqEvt const *)e)->accessType;
            me->bytesTotal = ((I2CWriteReqEvt const *)e)->bytes;
            me->addrSize   = I2C_getMemAddrSize(me->iDev);
            me->i2cDevOp   = I2C_OP_MEM_WRITE;

            /* If we are to print out the data we, need to do it before we copy it to the local
             * buffer or we'll end up losing it. */
            uint16_t tmpLen = 0;
            DC3Error_t err = CON_hexToStr(
                ((I2CWriteReqEvt const *)e)->dataBuf,// data to convert
                me->bytesTotal,                      // length of data to convert
                (char *)me->dataBuf,                 // where to write output
                sizeof(me->dataBuf),                 // max size of output buffer
                &tmpLen,                             // size of the resulting output
                0,                                   // no columns
                ' ',                                 // separator
                true                                 // bPrintX
            );

            LOG_printf( "Trying %s op to write to dev %s on I2CBus%d to at addr 0x%02x via Acc: %d\n",
                I2C_opToStr( me->i2cDevOp ), I2C_devToStr(me->iDev), me->iDev+1, me->addrStart, me->accessType );
            if ( ERR_NONE == err ) {
                LOG_printf( "Data to write (%d bytes): %s\n",
                    me->bytesTotal, me->dataBuf );
            } else {
                WRN_printf( "Data to write (%d bytes) too big to print due to buffer size (%d). Not shown\n",
                    ((I2CBusDataEvt const *)e)->dataLen,  sizeof(me->dataBuf) );
            }

            /* This event will disappear after it's handled so the data must be copied to local buffer*/
            MEMCPY( me->dataBuf, ((I2CWriteReqEvt const *)e)->dataBuf, me->bytesTotal );

            /* Allocate a WriteDone evt that will ALWAYS be sent out upon exit of the Busy state
             * for write operations. */
            me->i2cWriteDoneEvt = Q_NEW(I2CWriteDoneEvt, I2C1_DEV_WRITE_DONE_SIG);

            /* Fill out the fields that won't change or to just safe values in case of failure */
            me->i2cWriteDoneEvt->i2cDev = me->iDev;
            me->i2cWriteDoneEvt->bytes  = 0;

            status_ = Q_TRAN(&I2C1DevMgr_ValidateRequest);
            break;
        }
        default: {
            status_ = Q_SUPER(&I2C1DevMgr_Active);
            break;
        }
    }
    return status_;
}


/**
 * @} end addtogroup groupI2C
 */
/******** Copyright (C) 2014 Datacard. All rights reserved *****END OF FILE****/
