/*****************************************************************************
* Model: MainMgr.qm
* File:  ./MainMgr_gen.h
*
* This code has been generated by QM tool (see state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*****************************************************************************/
/*${.::MainMgr_gen.h} ......................................................*/
/**
 * @file    MainMgr.h
 * Definitions for functions for the MainMgr AO.  This file is heavily
 * based on the code auto-generated using MainMgr.qm model.  Please update
 * the model to reflect any manual changes to the code.
 *
 * Note: If editing this file, please make sure to update the MainMgr.qm
 * model.  The generated code from that model should be very similar to the code
 * in this file.
 *
 * @date    03/20/2015
 * @author  Harry Rostovtsev
 * @email   harry_rostovtsev@datacard.com
 * Copyright (C) 2015 Datacard. All rights reserved.
 *
 * @addtogroup groupClient
 * @{
 */
#ifndef MAINMGR_H_
#define MAINMGR_H_

using namespace std;

/* Includes ------------------------------------------------------------------*/
#include "qp_port.h"                                        /* for QP support */
#include "ClientShared.h"
#include "LogStub.h"
#include "comm.h"

/* Exported defines ----------------------------------------------------------*/
/* Exported macros -----------------------------------------------------------*/
/* Exported types ------------------------------------------------------------*/

/**
 * @brief Event type for exiting from MainMgr with an error code.
 */
/*${Events::ExitEvt} .......................................................*/
typedef struct {
/* protected: */
    QEvt super;

    /**< Error code that indicates the status of exit from this AO. */
    ClientError_t errorCode;
} ExitEvt;


/* Exported constants --------------------------------------------------------*/
/* Exported functions --------------------------------------------------------*/

/**
 * @brief C "constructor" for MainMgr "class".
 * Initializes all the timers and queues used by the AO, sets up a deferral
 * queue, and sets of the first state.
 * @param [in]: *log: LogStub pointer to a logging object.
 * @retval: none
 */
/*${AOs::MainMgr_ctor} .....................................................*/
void MainMgr_ctor(LogStub* log);


/**
 * @brief Sets a new connection.
 * This globally accesible function sets a new connection for MainMgr AO to use.
 * @param [in] *comm: comm pointer to a new connection object.
 * @retval: none
 */
/*${AOs::MainMgr_setConn} ..................................................*/
void MainMgr_setConn(comm* comm);


/**< "opaque" pointer to the Active Object */
extern QActive * const AO_MainMgr;


/**
 * @} end addtogroup groupClient
 */
#endif                                                          /* MAINMGR_H_ */
/******** Copyright (C) 2015 Datacard. All rights reserved *****END OF FILE****/

