/**
 * @file     DC3_comm_api.h
 *
 * DC3 Communications API typedefs and enum defs that are related to the
 * generated messages.  This file should be included by any project that wants
 * to communicate with the DC3 board via the debug channel. It includes all the
 * error definitions, timeouts, and messages.
 *
 * @date       03/19/2015
 * @author     Harry Rostovtsev
 * @email      harry_rostovtsev@datacard.com
 * Copyright (C) 2015 Datacard. All rights reserved.
 */
#ifndef CBCOMMAPI_H_
#define CBCOMMAPI_H_

#ifndef CBMSGS_H_
#define CBMSGS_H_
#include "CBMsgs.h"
#endif

#include "CBErrors.h"
#include "CBTimeouts.h"
#include "dfuse.h"
#include "util.h"

/* This is the MAX length of msgs in bytes that can be sent over serial to the
 * RFID board */
#define CB_MAX_MSG_LEN 256

/* These typedefs allow the project to use the enums defined in the autogenerated
 * protobuf files  */
//typedef enum RFIDMsgName         RFIDMsgName;
//typedef enum RFIDMsgType         RFIDMsgType;
//typedef enum RFIDMsgRoute        RFIDMsgRoute;
//typedef enum RFIDFieldState      RFIDFieldState;
//typedef enum RFIDBootMode        RFIDBootMode;

#endif                                                        /* CBCOMMAPI_H_ */
/******** Copyright (C) 2013 Datacard. All rights reserved *****END OF FILE****/
